package com.marta.admin.dto;

import java.util.Date;

public class BcwtPatronDTO implements java.io.Serializable{
	
	
//	 Fields    

    private Long patronid;
    private Long bcwtusertypeid;
    private String firstname;
    private String middlename;
    private String lastname;
    private String emailid;
    private String patronpassword;
    private String phonenumber;
    
    private Date dateofbirth;
    private String isautogenerated;
    private String lockstatus;
    private String activestatus;
    private Integer logincount;
    private String lastlogintime;
    private Long parentpatronid;
    private String role;
    private String notes;
    private Long companyid;
    private String companyname;
    
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	
	public String getNotes() {
		return notes;
	}
	public void setNotes(String notes) {
		this.notes = notes;
	}
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
	public Long getParentpatronid() {
		return parentpatronid;
	}
	public void setParentpatronid(Long parentpatronid) {
		this.parentpatronid = parentpatronid;
	}
	public Long getBcwtusertypeid() {
		return bcwtusertypeid;
	}
	public void setBcwtusertypeid(Long bcwtusertypeid) {
		this.bcwtusertypeid = bcwtusertypeid;
	}
	
	/**
	 * @return the dateofbirth
	 */
	public Date getDateofbirth() {
		return dateofbirth;
	}
	/**
	 * @param dateofbirth the dateofbirth to set
	 */
	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}
	public String getEmailid() {
		return emailid;
	}
	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getIsautogenerated() {
		return isautogenerated;
	}
	public void setIsautogenerated(String isautogenerated) {
		this.isautogenerated = isautogenerated;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getLockstatus() {
		return lockstatus;
	}
	public void setLockstatus(String lockstatus) {
		this.lockstatus = lockstatus;
	}
	public Integer getLogincount() {
		return logincount;
	}
	public void setLogincount(Integer logincount) {
		this.logincount = logincount;
	}
	public String getMiddlename() {
		return middlename;
	}
	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}
	
	public String getPatronpassword() {
		return patronpassword;
	}
	public void setPatronpassword(String patronpassword) {
		this.patronpassword = patronpassword;
	}
	public Long getPatronid() {
		return patronid;
	}
	public void setPatronid(Long patronid) {
		this.patronid = patronid;
	}
	public String getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
	public String getActivestatus() {
		return activestatus;
	}
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}
	public String getLastlogintime() {
		return lastlogintime;
	}
	public void setLastlogintime(String lastlogintime) {
		this.lastlogintime = lastlogintime;
	}
	public Long getCompanyid() {
		return companyid;
	}
	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}

}
