package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtproduct generated by MyEclipse - Hibernate Tools
 */

public class BcwtProduct  implements java.io.Serializable {


    // Fields

     private Long productid;
     private Long fare_instrument_id;
     private BcwtRegion bcwtregion;
     private String productname;
     private String productdescription;
     private Integer riderclassification;
     private Double price;
     private Set bcwtbreezecardproducts = new HashSet(0);
     private Integer sortorder;
     private String productdetaildesc;
     private String activestatus;

    // Constructors

    public String getActivestatus() {
		return activestatus;
	}



	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}



	/**
	 * @return the productdetaildesc
	 */
	public String getProductdetaildesc() {
		return productdetaildesc;
	}



	/**
	 * @param productdetaildesc the productdetaildesc to set
	 */
	public void setProductdetaildesc(String productdetaildesc) {
		this.productdetaildesc = productdetaildesc;
	}



	public Integer getSortorder() {
		return sortorder;
	}



	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}



	/** default constructor */
    public BcwtProduct() {
    }



    // Property accessors

    public Long getProductid() {
        return this.productid;
    }

    public void setProductid(Long productid) {
        this.productid = productid;
    }

    public String getProductname() {
        return this.productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getProductdescription() {
        return this.productdescription;
    }

    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Set getBcwtbreezecardproducts() {
        return this.bcwtbreezecardproducts;
    }

    public void setBcwtbreezecardproducts(Set bcwtbreezecardproducts) {
        this.bcwtbreezecardproducts = bcwtbreezecardproducts;
    }



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */

	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((productid == null) ? 0 : productid.hashCode());
		return result;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtProduct other = (BcwtProduct) obj;
		if (productid == null) {
			if (other.productid != null)
				return false;
		} else if (!productid.equals(other.productid))
			return false;
		return true;
	}



	public Long getFare_instrument_id() {
		return fare_instrument_id;
	}



	public void setFare_instrument_id(Long fare_instrument_id) {
		this.fare_instrument_id = fare_instrument_id;
	}



	public BcwtRegion getBcwtregion() {
		return bcwtregion;
	}



	public void setBcwtregion(BcwtRegion bcwtregion) {
		this.bcwtregion = bcwtregion;
	}



	/**
	 * @return the riderclassification
	 */
	public Integer getRiderclassification() {
		return riderclassification;
	}



	/**
	 * @param riderclassification the riderclassification to set
	 */
	public void setRiderclassification(Integer riderclassification) {
		this.riderclassification = riderclassification;
	}



	

}