package com.marta.admin.hibernate;



/**
 * BcwtshippingId generated by MyEclipse - Hibernate Tools
 */

public class BcwtShipping  implements java.io.Serializable {


    // Fields    

     private Long shippingid;
     private Long minnoofproduct;
     private Long maxnoofproduct;
     private String weight;
     private String shippingcharge;
     private String modeofshipping;
     private String activestatus;

    
    // Property accessors

    public Long getShippingid() {
        return this.shippingid;
    }
    
    public void setShippingid(Long shippingid) {
        this.shippingid = shippingid;
    }

    public Long getMinnoofproduct() {
        return this.minnoofproduct;
    }
    
    public void setMinnoofproduct(Long minnoofproduct) {
        this.minnoofproduct = minnoofproduct;
    }

    public Long getMaxnoofproduct() {
        return this.maxnoofproduct;
    }
    
    public void setMaxnoofproduct(Long maxnoofproduct) {
        this.maxnoofproduct = maxnoofproduct;
    }

    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getShippingcharge() {
        return this.shippingcharge;
    }
    
    public void setShippingcharge(String shippingcharge) {
        this.shippingcharge = shippingcharge;
    }

    public String getModeofshipping() {
        return this.modeofshipping;
    }
    
    public void setModeofshipping(String modeofshipping) {
        this.modeofshipping = modeofshipping;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BcwtShipping) ) return false;
		 BcwtShipping castOther = ( BcwtShipping ) other; 
         
		 return ( (this.getShippingid()==castOther.getShippingid()) || ( this.getShippingid()!=null && castOther.getShippingid()!=null && this.getShippingid().equals(castOther.getShippingid()) ) )
 && ( (this.getMinnoofproduct()==castOther.getMinnoofproduct()) || ( this.getMinnoofproduct()!=null && castOther.getMinnoofproduct()!=null && this.getMinnoofproduct().equals(castOther.getMinnoofproduct()) ) )
 && ( (this.getMaxnoofproduct()==castOther.getMaxnoofproduct()) || ( this.getMaxnoofproduct()!=null && castOther.getMaxnoofproduct()!=null && this.getMaxnoofproduct().equals(castOther.getMaxnoofproduct()) ) )
 && ( (this.getWeight()==castOther.getWeight()) || ( this.getWeight()!=null && castOther.getWeight()!=null && this.getWeight().equals(castOther.getWeight()) ) )
 && ( (this.getShippingcharge()==castOther.getShippingcharge()) || ( this.getShippingcharge()!=null && castOther.getShippingcharge()!=null && this.getShippingcharge().equals(castOther.getShippingcharge()) ) )
 && ( (this.getModeofshipping()==castOther.getModeofshipping()) || ( this.getModeofshipping()!=null && castOther.getModeofshipping()!=null && this.getModeofshipping().equals(castOther.getModeofshipping()) ) )
 && ( (this.getActivestatus()==castOther.getActivestatus()) || ( this.getActivestatus()!=null && castOther.getActivestatus()!=null && this.getActivestatus().equals(castOther.getActivestatus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getShippingid() == null ? 0 : this.getShippingid().hashCode() );
         result = 37 * result + ( getMinnoofproduct() == null ? 0 : this.getMinnoofproduct().hashCode() );
         result = 37 * result + ( getMaxnoofproduct() == null ? 0 : this.getMaxnoofproduct().hashCode() );
         result = 37 * result + ( getWeight() == null ? 0 : this.getWeight().hashCode() );
         result = 37 * result + ( getShippingcharge() == null ? 0 : this.getShippingcharge().hashCode() );
         result = 37 * result + ( getModeofshipping() == null ? 0 : this.getModeofshipping().hashCode() );
         result = 37 * result + ( getActivestatus() == null ? 0 : this.getActivestatus().hashCode() );
         return result;
   }   





}