package com.marta.admin.hibernate;

import java.util.Date;


/**
 * BcwtThreshold generated by MyEclipse - Hibernate Tools
 */

public class BcwtThreshold  implements java.io.Serializable {


    // Fields
	 
	private static final long serialVersionUID = 1L;
	private Long thresholdid;
	private BcwtPatronBreezeCard bcwtpatronbreezecard;
	private BcwtPatronPaymentCards bcwtpatronpaymentcards;
	private Double thresholdlimit;
	private Double thresholdcashvalue;
	private Date thresholddate;
	private String thresholdstatus;
	private String activestatus;
	private Long orderid;
	private Integer eventid;
	
	public Integer getEventid() {
		return eventid;
	}



	public void setEventid(Integer eventid) {
		this.eventid = eventid;
	}



	public String getActivestatus() {
		return activestatus;
	}
	
	
	
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}
	
	
	
	public BcwtPatronBreezeCard getBcwtpatronbreezecard() {
		return bcwtpatronbreezecard;
	}
	
	
	
	public void setBcwtpatronbreezecard(BcwtPatronBreezeCard bcwtpatronbreezecard) {
		this.bcwtpatronbreezecard = bcwtpatronbreezecard;
	}
	
	
	
	public BcwtPatronPaymentCards getBcwtpatronpaymentcards() {
		return bcwtpatronpaymentcards;
	}
	
	
	
	public void setBcwtpatronpaymentcards(
			BcwtPatronPaymentCards bcwtpatronpaymentcards) {
		this.bcwtpatronpaymentcards = bcwtpatronpaymentcards;
	}
	
	
	
	public Long getOrderid() {
		return orderid;
	}
	
	
	
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}
	
	
	
	public Double getThresholdcashvalue() {
		return thresholdcashvalue;
	}
	
	
	
	public void setThresholdcashvalue(Double thresholdcashvalue) {
		this.thresholdcashvalue = thresholdcashvalue;
	}
	
	
	
	public Date getThresholddate() {
		return thresholddate;
	}
	
	
	
	public void setThresholddate(Date thresholddate) {
		this.thresholddate = thresholddate;
	}
	
	
	
	public Long getThresholdid() {
		return this.thresholdid;
	}
	
	
	
	public void setThresholdid(Long thresholdid) {
		this.thresholdid = thresholdid;
	}
	
	
	
	public Double getThresholdlimit() {
		return thresholdlimit;
	}
	
	
	
	public void setThresholdlimit(Double thresholdlimit) {
		this.thresholdlimit = thresholdlimit;
	}
	
	
	
	public String getThresholdstatus() {
		return thresholdstatus;
	}
	
	
	
	public void setThresholdstatus(String thresholdstatus) {
		this.thresholdstatus = thresholdstatus;
	}
	
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((thresholdid == null) ? 0 : thresholdid.hashCode());
		return result;
	}
	
	
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtThreshold other = (BcwtThreshold) obj;
		if (thresholdid == null) {
			if (other.thresholdid != null)
				return false;
		} else if (!thresholdid.equals(other.thresholdid))
			return false;
		return true;
	}


}