package com.marta.admin.hibernate;

/**
 * BcwtsGbsDiscount generated by MyEclipse - Hibernate Tools
 */

public class BcwtsGbsDiscount  implements java.io.Serializable {


    // Fields    
	private static final long serialVersionUID = 1L;
	private Long gbsdiscountid;
	private String minrange;
	private String maxrange;
	private Double discount;
	private String activestatus;


    // Constructors

    /** default constructor */
    public BcwtsGbsDiscount() {
    }

    
    /** full constructor */
    public BcwtsGbsDiscount(String minrange, String maxrange, Double discount, String activestatus) {
        this.minrange = minrange;
        this.maxrange = maxrange;
        this.discount = discount;
        this.activestatus = activestatus;
    }

   
    // Property accessors

    public Long getGbsdiscountid() {
        return this.gbsdiscountid;
    }
    
    public void setGbsdiscountid(Long gbsdiscountid) {
        this.gbsdiscountid = gbsdiscountid;
    }

    public String getMinrange() {
        return this.minrange;
    }
    
    public void setMinrange(String minrange) {
        this.minrange = minrange;
    }

    public String getMaxrange() {
        return this.maxrange;
    }
    
    public void setMaxrange(String maxrange) {
        this.maxrange = maxrange;
    }

    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }
   








}