package com.marta.admin.hibernate;



/**
 * Bcwtpartnerproductdetails generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerProductDetails  implements java.io.Serializable {

     private Long partnerproductid;
     private BcwtPartnerOrderInfo bcwtpartnerorderinfo;
     private Long productid;
     private String addvaluestatus;

    /**
	 * @return the addvaluestatus
	 */
	public String getAddvaluestatus() {
		return addvaluestatus;
	}
	/**
	 * @param addvaluestatus the addvaluestatus to set
	 */
	public void setAddvaluestatus(String addvaluestatus) {
		this.addvaluestatus = addvaluestatus;
	}
	/**
	 * @return the bcwtpartnerorderinfo
	 */
	public BcwtPartnerOrderInfo getBcwtpartnerorderinfo() {
		return bcwtpartnerorderinfo;
	}
	/**
	 * @param bcwtpartnerorderinfo the bcwtpartnerorderinfo to set
	 */
	public void setBcwtpartnerorderinfo(BcwtPartnerOrderInfo bcwtpartnerorderinfo) {
		this.bcwtpartnerorderinfo = bcwtpartnerorderinfo;
	}
	/**
	 * @return the partnerproductid
	 */
	public Long getPartnerproductid() {
		return partnerproductid;
	}
	/**
	 * @param partnerproductid the partnerproductid to set
	 */
	public void setPartnerproductid(Long partnerproductid) {
		this.partnerproductid = partnerproductid;
	}
	/**
	 * @return the productid
	 */
	public Long getProductid() {
		return productid;
	}
	/**
	 * @param productid the productid to set
	 */
	public void setProductid(Long productid) {
		this.productid = productid;
	}

}