package com.marta.admin.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtevents generated by MyEclipse - Hibernate Tools
 */

public class BcwtEvents  implements java.io.Serializable {


    // Fields    

     private Long eventid;
     private BcwtPatron bcwtpatron;
     private String eventname;
     private Date eventstartdate;
     private Date eventenddate;
     private String location;
     private String note;
     private String activestatus;
     private Date createddate;
     private Set bcwtorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtEvents() {
    }

	/** minimal constructor */
    public BcwtEvents(BcwtPatron bcwtpatron, String eventname, Date eventstartdate, Date eventenddate, String location, Date createddate) {
        this.bcwtpatron = bcwtpatron;
        this.eventname = eventname;
        this.eventstartdate = eventstartdate;
        this.eventenddate = eventenddate;
        this.location = location;
        this.createddate = createddate;
    }
    
    /** full constructor */
    public BcwtEvents(BcwtPatron bcwtpatron, String eventname, Date eventstartdate, Date eventenddate, String location, String activestatus, Date createddate, Set bcwtorders) {
        this.bcwtpatron = bcwtpatron;
        this.eventname = eventname;
        this.eventstartdate = eventstartdate;
        this.eventenddate = eventenddate;
        this.location = location;
        this.activestatus = activestatus;
        this.createddate = createddate;
        this.bcwtorders = bcwtorders;
    }

   
    // Property accessors

    public Long getEventid() {
        return this.eventid;
    }
    
    public void setEventid(Long eventid) {
        this.eventid = eventid;
    }

    public BcwtPatron getBcwtpatron() {
        return this.bcwtpatron;
    }
    
    public void setBcwtpatron(BcwtPatron bcwtpatron) {
        this.bcwtpatron = bcwtpatron;
    }

    public String getEventname() {
        return this.eventname;
    }
    
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    public Date getEventstartdate() {
        return this.eventstartdate;
    }
    
    public void setEventstartdate(Date eventstartdate) {
        this.eventstartdate = eventstartdate;
    }

    public Date getEventenddate() {
        return this.eventenddate;
    }
    
    public void setEventenddate(Date eventenddate) {
        this.eventenddate = eventenddate;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }

    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public Set getBcwtorders() {
        return this.bcwtorders;
    }
    
    public void setBcwtorders(Set bcwtorders) {
        this.bcwtorders = bcwtorders;
    }

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}
   








}