package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwtcancelledorder generated by MyEclipse - Hibernate Tools
 */

public class BcwtCancelledOrder  implements java.io.Serializable {


    // Fields    

     private Long cancelledorderid;
     private BcwtOrder bcwtorder;
     private BcwtReasonType bcwtreasontype;
     private String note;
     private Date cancelleddate;
     private String cancelledby;
     private String activestatus;


    // Constructors

    /** default constructor */
    public BcwtCancelledOrder() {
    }

	/** minimal constructor */
    public BcwtCancelledOrder(String activestatus) {
        this.activestatus = activestatus;
    }
    
    /** full constructor */
    public BcwtCancelledOrder(BcwtOrder bcwtorder, BcwtReasonType bcwtreasontype, String note, Date cancelleddate, String cancelledby, String activestatus) {
        this.bcwtorder = bcwtorder;
        this.bcwtreasontype = bcwtreasontype;
        this.note = note;
        this.cancelleddate = cancelleddate;
        this.cancelledby = cancelledby;
        this.activestatus = activestatus;
    }

   
    // Property accessors

    public Long getCancelledorderid() {
        return this.cancelledorderid;
    }
    
    public void setCancelledorderid(Long cancelledorderid) {
        this.cancelledorderid = cancelledorderid;
    }

    public BcwtOrder getBcwtorder() {
        return this.bcwtorder;
    }
    
    public void setBcwtorder(BcwtOrder bcwtorder) {
        this.bcwtorder = bcwtorder;
    }

    public BcwtReasonType getBcwtreasontype() {
        return this.bcwtreasontype;
    }
    
    public void setBcwtreasontype(BcwtReasonType bcwtreasontype) {
        this.bcwtreasontype = bcwtreasontype;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public Date getCancelleddate() {
        return this.cancelleddate;
    }
    
    public void setCancelleddate(Date cancelleddate) {
        this.cancelleddate = cancelleddate;
    }

    public String getCancelledby() {
        return this.cancelledby;
    }
    
    public void setCancelledby(String cancelledby) {
        this.cancelledby = cancelledby;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }
   








}