package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwtcashrecurring generated by MyEclipse - Hibernate Tools
 */

public class BcwtCashRecurring  implements java.io.Serializable {


    // Fields

     private Long cashrecurringid;
     private BcwtPatronBreezeCard bcwtpatronbreezecard;
     private Double recurringcashvalue;
     private String recurringfrequency;
     private String recurringdayofweek;
     private String recurringdayofmonth;
     private Date datecashadded;
     private String cashrecuringstatus;
     private String activestatus;
     private Long orderid;
     private BcwtPatronPaymentCards bcwtpatronpaymentcards;
     private Date lastrundate;
     private Date nextrundate;

    // Constructors

    public BcwtPatronPaymentCards getBcwtpatronpaymentcards() {
		return bcwtpatronpaymentcards;
	}


	public void setBcwtpatronpaymentcards(
			BcwtPatronPaymentCards bcwtpatronpaymentcards) {
		this.bcwtpatronpaymentcards = bcwtpatronpaymentcards;
	}


	public Date getLastrundate() {
		return lastrundate;
	}


	public void setLastrundate(Date lastrundate) {
		this.lastrundate = lastrundate;
	}


	public Date getNextrundate() {
		return nextrundate;
	}


	public void setNextrundate(Date nextrundate) {
		this.nextrundate = nextrundate;
	}


	/** default constructor */
    public BcwtCashRecurring() {
    }


    // Property accessors

    public Long getCashrecurringid() {
        return this.cashrecurringid;
    }

    public void setCashrecurringid(Long cashrecurringid) {
        this.cashrecurringid = cashrecurringid;
    }

    public BcwtPatronBreezeCard getBcwtpatronbreezecard() {
        return this.bcwtpatronbreezecard;
    }

    public void setBcwtpatronbreezecard(BcwtPatronBreezeCard bcwtpatronbreezecard) {
        this.bcwtpatronbreezecard = bcwtpatronbreezecard;
    }

    public Double getRecurringcashvalue() {
        return this.recurringcashvalue;
    }

    public void setRecurringcashvalue(Double recurringcashvalue) {
        this.recurringcashvalue = recurringcashvalue;
    }

    public String getRecurringfrequency() {
        return this.recurringfrequency;
    }

    public void setRecurringfrequency(String recurringfrequency) {
        this.recurringfrequency = recurringfrequency;
    }

    public String getRecurringdayofweek() {
        return this.recurringdayofweek;
    }

    public void setRecurringdayofweek(String recurringdayofweek) {
        this.recurringdayofweek = recurringdayofweek;
    }

    public String getRecurringdayofmonth() {
        return this.recurringdayofmonth;
    }

    public void setRecurringdayofmonth(String recurringdayofmonth) {
        this.recurringdayofmonth = recurringdayofmonth;
    }

    public Date getDatecashadded() {
        return this.datecashadded;
    }

    public void setDatecashadded(Date datecashadded) {
        this.datecashadded = datecashadded;
    }

    public String getActivestatus() {
		return activestatus;
	}


	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}


	public Long getOrderid() {
		return orderid;
	}


	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}

	public String getCashrecuringstatus() {
		return cashrecuringstatus;
	}


	public void setCashrecuringstatus(String cashrecuringstatus) {
		this.cashrecuringstatus = cashrecuringstatus;
	}	
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */

	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((cashrecurringid == null) ? 0 : cashrecurringid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtCashRecurring other = (BcwtCashRecurring) obj;
		if (cashrecurringid == null) {
			if (other.cashrecurringid != null)
				return false;
		} else if (!cashrecurringid.equals(other.cashrecurringid))
			return false;
		return true;
	}

}