package com.marta.admin.hibernate;



/**
 * BcwtProductAccntNumsId generated by MyEclipse - Hibernate Tools
 */

public class BcwtProductAccntNumsId  implements java.io.Serializable {


    // Fields    

     private Long bcwtsProductAccntNumsId;
     private Long fareInstrumentId;
     private String productname;


    // Constructors

    /** default constructor */
    public BcwtProductAccntNumsId() {
    }

    
    /** full constructor */
    public BcwtProductAccntNumsId(Long bcwtsProductAccntNumsId, Long fareInstrumentId, String productname) {
        this.bcwtsProductAccntNumsId = bcwtsProductAccntNumsId;
        this.fareInstrumentId = fareInstrumentId;
        this.productname = productname;
    }

   
    // Property accessors

    public Long getBcwtsProductAccntNumsId() {
        return this.bcwtsProductAccntNumsId;
    }
    
    public void setBcwtsProductAccntNumsId(Long bcwtsProductAccntNumsId) {
        this.bcwtsProductAccntNumsId = bcwtsProductAccntNumsId;
    }

    public Long getFareInstrumentId() {
        return this.fareInstrumentId;
    }
    
    public void setFareInstrumentId(Long fareInstrumentId) {
        this.fareInstrumentId = fareInstrumentId;
    }

    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }  



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BcwtProductAccntNumsId) ) return false;
		 BcwtProductAccntNumsId castOther = ( BcwtProductAccntNumsId ) other; 
         
		 return ( (this.getBcwtsProductAccntNumsId()==castOther.getBcwtsProductAccntNumsId()) || ( this.getBcwtsProductAccntNumsId()!=null && castOther.getBcwtsProductAccntNumsId()!=null && this.getBcwtsProductAccntNumsId().equals(castOther.getBcwtsProductAccntNumsId()) ) )
 && ( (this.getFareInstrumentId()==castOther.getFareInstrumentId()) || ( this.getFareInstrumentId()!=null && castOther.getFareInstrumentId()!=null && this.getFareInstrumentId().equals(castOther.getFareInstrumentId()) ) )
 && ( (this.getProductname()==castOther.getProductname()) || ( this.getProductname()!=null && castOther.getProductname()!=null && this.getProductname().equals(castOther.getProductname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBcwtsProductAccntNumsId() == null ? 0 : this.getBcwtsProductAccntNumsId().hashCode() );
         result = 37 * result + ( getFareInstrumentId() == null ? 0 : this.getFareInstrumentId().hashCode() );
         result = 37 * result + ( getProductname() == null ? 0 : this.getProductname().hashCode() );
         return result;
   }   





}