package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwtpartnerreturnedorder generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerReturnedOrder  implements java.io.Serializable {


    // Fields

     private Long returnedorderid;
     private PartnerCardOrder partnercardorder;
     private BcwtReasonType bcwtreasontype;
     private String note;
     private Date returneddate;
     private String updatedby;
     private String activestatus;
     private Long noofdeliveryattempts;

	public String getActivestatus() {
		return activestatus;
	}
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}
	public BcwtReasonType getBcwtreasontype() {
		return bcwtreasontype;
	}
	public void setBcwtreasontype(BcwtReasonType bcwtreasontype) {
		this.bcwtreasontype = bcwtreasontype;
	}
	public Long getNoofdeliveryattempts() {
		return noofdeliveryattempts;
	}
	public void setNoofdeliveryattempts(Long noofdeliveryattempts) {
		this.noofdeliveryattempts = noofdeliveryattempts;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public PartnerCardOrder getPartnercardorder() {
		return partnercardorder;
	}
	public void setPartnercardorder(PartnerCardOrder partnercardorder) {
		this.partnercardorder = partnercardorder;
	}
	public Date getReturneddate() {
		return returneddate;
	}
	public void setReturneddate(Date returneddate) {
		this.returneddate = returneddate;
	}
	public Long getReturnedorderid() {
		return returnedorderid;
	}
	public void setReturnedorderid(Long returnedorderid) {
		this.returnedorderid = returnedorderid;
	}
	public String getUpdatedby() {
		return updatedby;
	}
	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}











}