package com.marta.admin.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtorder generated by MyEclipse - Hibernate Tools
 */

public class BcwtOrder implements java.io.Serializable {

	// Fields
     private Long orderid;
     private BcwtOrderStatus bcwtorderstatus;
     private BcwtPatronPaymentCards bcwtpatronpaymentcards;
     private BcwtPatronAddress bcwtpatronaddress;
     private Date orderdate;
     private Double ordervalue;
     private Double shippingamount;
     private BcwtPatron bcwtpatron;
     private String consignmentnumber;
     private BcwtEvents bcwtevents;
     private BcwtPatron processedBy;
     private String orderType;
     private Date shippeddate;
     private Date transactiondate;
     private String paymentAuthorization;
     private String skipAuthorizationNotes;
     private Double priceofbreezecard;
     private Set bcwtorderdetailses = new HashSet(0);
     private Set bcwtorderinfo = new HashSet(0);

    // Constructors
    /** default constructor */
    public BcwtOrder() {
    }

    // Property accessors

    public Long getOrderid() {
        return this.orderid;
    }

    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    public BcwtOrderStatus getBcwtorderstatus() {
        return this.bcwtorderstatus;
    }

    public void setBcwtorderstatus(BcwtOrderStatus bcwtorderstatus) {
        this.bcwtorderstatus = bcwtorderstatus;
    }

    public BcwtPatronPaymentCards getBcwtpatronpaymentcards() {
        return this.bcwtpatronpaymentcards;
    }

    public void setBcwtpatronpaymentcards(BcwtPatronPaymentCards bcwtpatronpaymentcards) {
        this.bcwtpatronpaymentcards = bcwtpatronpaymentcards;
    }

    public BcwtPatronAddress getBcwtpatronaddress() {
        return this.bcwtpatronaddress;
    }

    public void setBcwtpatronaddress(BcwtPatronAddress bcwtpatronaddress) {
        this.bcwtpatronaddress = bcwtpatronaddress;
    }

    public Date getOrderdate() {
        return this.orderdate;
    }

    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    public Double getOrdervalue() {
        return this.ordervalue;
    }

    public void setOrdervalue(Double ordervalue) {
        this.ordervalue = ordervalue;
    }

    public Set getBcwtorderdetailses() {
        return this.bcwtorderdetailses;
    }

    public void setBcwtorderdetailses(Set bcwtorderdetailses) {
        this.bcwtorderdetailses = bcwtorderdetailses;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((orderid == null) ? 0 : orderid.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtOrder other = (BcwtOrder) obj;
		if (orderid == null) {
			if (other.orderid != null)
				return false;
		} else if (!orderid.equals(other.orderid))
			return false;
		return true;
	}

	/**
	 * @return the bcwtpatron
	 */
	public BcwtPatron getBcwtpatron() {
		return bcwtpatron;
	}



	/**
	 * @param bcwtpatron the bcwtpatron to set
	 */
	public void setBcwtpatron(BcwtPatron bcwtpatron) {
		this.bcwtpatron = bcwtpatron;
	}

	public Double getShippingamount() {
		return shippingamount;
	}

	public void setShippingamount(Double shippingamount) {
		this.shippingamount = shippingamount;
	}

	public BcwtEvents getBcwtevents() {
		return bcwtevents;
	}

	public void setBcwtevents(BcwtEvents bcwtevents) {
		this.bcwtevents = bcwtevents;
	}

	/**
	 * @return the processedBy
	 */
	public BcwtPatron getProcessedBy() {
		return processedBy;
	}

	/**
	 * @param processedBy the processedBy to set
	 */
	public void setProcessedBy(BcwtPatron processedBy) {
		this.processedBy = processedBy;
	}

	public String getOrderType() {
		return orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	public Set getBcwtorderinfo() {
		return bcwtorderinfo;
	}

	public void setBcwtorderinfo(Set bcwtorderinfo) {
		this.bcwtorderinfo = bcwtorderinfo;
	}

	public Date getShippeddate() {
		return shippeddate;
	}

	public void setShippeddate(Date shippeddate) {
		this.shippeddate = shippeddate;
	}

	public String getConsignmentnumber() {
		return consignmentnumber;
	}

	public void setConsignmentnumber(String consignmentnumber) {
		this.consignmentnumber = consignmentnumber;
	}

	/**
	 * @return the paymentAuthorization
	 */
	public String getPaymentAuthorization() {
		return paymentAuthorization;
	}

	/**
	 * @param paymentAuthorization the paymentAuthorization to set
	 */
	public void setPaymentAuthorization(String paymentAuthorization) {
		this.paymentAuthorization = paymentAuthorization;
	}

	/**
	 * @return the skipAuthorizationNotes
	 */
	public String getSkipAuthorizationNotes() {
		return skipAuthorizationNotes;
	}

	/**
	 * @param skipAuthorizationNotes the skipAuthorizationNotes to set
	 */
	public void setSkipAuthorizationNotes(String skipAuthorizationNotes) {
		this.skipAuthorizationNotes = skipAuthorizationNotes;
	}

	/**
	 * @return the transactiondate
	 */
	public Date getTransactiondate() {
		return transactiondate;
	}

	/**
	 * @param transactiondate the transactiondate to set
	 */
	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}

	/**
	 * @return the priceofbreezecard
	 */
	public Double getPriceofbreezecard() {
		return priceofbreezecard;
	}

	/**
	 * @param priceofbreezecard the priceofbreezecard to set
	 */
	public void setPriceofbreezecard(Double priceofbreezecard) {
		this.priceofbreezecard = priceofbreezecard;
	}

}