package com.marta.admin.hibernate;



/**
 * Bcwtreports generated by MyEclipse - Hibernate Tools
 */

public class BcwtReports  implements java.io.Serializable {


    // Fields    

     private Long reportid;
     private String reportname;
     private String activestatus;


    // Constructors

    /** default constructor */
    public BcwtReports() {
    }

    
    /** full constructor */
    public BcwtReports(String reportname, String activestatus) {
        this.reportname = reportname;
        this.activestatus = activestatus;
    }

   
    // Property accessors

    public Long getReportid() {
        return this.reportid;
    }
    
    public void setReportid(Long reportid) {
        this.reportid = reportid;
    }

    public String getReportname() {
        return this.reportname;
    }
    
    public void setReportname(String reportname) {
        this.reportname = reportname;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }
   








}