package com.marta.admin.hibernate;


/**
 * BcwtGbsDiscountProduct generated by MyEclipse - Hibernate Tools
 */

public class BcwtGbsDiscountProduct  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long gbsdiscountproductid;
	private BcwtProduct bcwtproduct;
	private String activestatus;


    // Constructors

    /** default constructor */
    public BcwtGbsDiscountProduct() {
    }

    
    /** full constructor */
    public BcwtGbsDiscountProduct(BcwtProduct bcwtproduct, String activestatus) {
        this.bcwtproduct = bcwtproduct;
        this.activestatus = activestatus;
    }

   
    // Property accessors

    public Long getGbsdiscountproductid() {
        return this.gbsdiscountproductid;
    }
    
    public void setGbsdiscountproductid(Long gbsdiscountproductid) {
        this.gbsdiscountproductid = gbsdiscountproductid;
    }

    public BcwtProduct getBcwtproduct() {
        return this.bcwtproduct;
    }
    
    public void setBcwtproduct(BcwtProduct bcwtproduct) {
        this.bcwtproduct = bcwtproduct;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }
   








}