package com.marta.admin.hibernate;



/**
 * Bcwtconfigparams generated by MyEclipse - Hibernate Tools
 */

public class BcwtConfigParams  implements java.io.Serializable {


    // Fields

     private Long configid;
     private String configname;
     private String paramvalue;
     private String defaultvalue;
     private String activestatus;


    // Constructors

    /** default constructor */
    public BcwtConfigParams() {
    }


    // Property accessors

    public Long getConfigid() {
        return this.configid;
    }

    public void setConfigid(Long configid) {
        this.configid = configid;
    }

    public String getConfigname() {
        return this.configname;
    }

    public void setConfigname(String configname) {
        this.configname = configname;
    }

    public String getParamvalue() {
        return this.paramvalue;
    }

    public void setParamvalue(String paramvalue) {
        this.paramvalue = paramvalue;
    }

    public String getDefaultvalue() {
        return this.defaultvalue;
    }

    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    public String getActivestatus() {
        return this.activestatus;
    }

    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((configid == null) ? 0 : configid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtConfigParams other = (BcwtConfigParams) obj;
		if (configid == null) {
			if (other.configid != null)
				return false;
		} else if (!configid.equals(other.configid))
			return false;
		return true;
	}


}