package com.marta.admin.hibernate;



/**
 * Bcwtpwdverifiy generated by MyEclipse - Hibernate Tools
 */

public class BcwtPwdVerifiy  implements java.io.Serializable {


    // Fields

     private Long pwdverifyid;
     private BcwtPatron bcwtpatron;
     private BcwtSecretQuestions bcwtsecretquestions;
     private String answer;


    // Constructors

    /** default constructor */
    public BcwtPwdVerifiy() {
    }


    // Property accessors

    public Long getPwdverifyid() {
        return this.pwdverifyid;
    }

    public void setPwdverifyid(Long pwdverifyid) {
        this.pwdverifyid = pwdverifyid;
    }

    public BcwtPatron getBcwtpatron() {
        return this.bcwtpatron;
    }

    public void setBcwtpatron(BcwtPatron bcwtpatron) {
        this.bcwtpatron = bcwtpatron;
    }

    public BcwtSecretQuestions getBcwtsecretquestions() {
        return this.bcwtsecretquestions;
    }

    public void setBcwtsecretquestions(BcwtSecretQuestions bcwtsecretquestions) {
        this.bcwtsecretquestions = bcwtsecretquestions;
    }

    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((pwdverifyid == null) ? 0 : pwdverifyid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtPwdVerifiy other = (BcwtPwdVerifiy) obj;
		if (pwdverifyid == null) {
			if (other.pwdverifyid != null)
				return false;
		} else if (!pwdverifyid.equals(other.pwdverifyid))
			return false;
		return true;
	}

	
}