package com.marta.admin.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtpartnerorderinfo generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerOrderInfo  implements java.io.Serializable {


    // Fields    

     private Long partnerorderinfoid;
     private BcwtShipmentmethods bcwtshipmentmethods;
     private PartnerCardOrder partnerCardorder;
     private Long noofcards;
     private String ordervalue;
     private Double cashvalue;
     private Double shippingamount;
     private Date shippeddate;
     private Long nextfareorderid;
     private Long batchid;
     private Set bcwtpartnerproductdetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtPartnerOrderInfo() {
    }

	/** minimal constructor */
    public BcwtPartnerOrderInfo(Long partnerorderinfoid, PartnerCardOrder partnerCardorder) {
        this.partnerorderinfoid = partnerorderinfoid;
        this.partnerCardorder = partnerCardorder;
    }
    
    /** full constructor */
    public BcwtPartnerOrderInfo(Long partnerorderinfoid, BcwtShipmentmethods bcwtshipmentmethods, PartnerCardOrder partnerCardorder, Long noofcards, String ordervalue, Double cashvalue, Double shippingamount, Date shippeddate, Long nextfareorderid, Long batchid, Set bcwtpartnerproductdetailses) {
        this.partnerorderinfoid = partnerorderinfoid;
        this.bcwtshipmentmethods = bcwtshipmentmethods;
        this.partnerCardorder = partnerCardorder;
        this.noofcards = noofcards;
        this.ordervalue = ordervalue;
        this.cashvalue = cashvalue;
        this.shippingamount = shippingamount;
        this.shippeddate = shippeddate;
        this.nextfareorderid = nextfareorderid;
        this.batchid = batchid;
        this.bcwtpartnerproductdetailses = bcwtpartnerproductdetailses;
    }

   
    // Property accessors

    public Long getPartnerorderinfoid() {
        return this.partnerorderinfoid;
    }
    
    public void setPartnerorderinfoid(Long partnerorderinfoid) {
        this.partnerorderinfoid = partnerorderinfoid;
    }

    public BcwtShipmentmethods getBcwtshipmentmethods() {
        return this.bcwtshipmentmethods;
    }
    
    public void setBcwtshipmentmethods(BcwtShipmentmethods bcwtshipmentmethods) {
        this.bcwtshipmentmethods = bcwtshipmentmethods;
    }

    public PartnerCardOrder getPartnerCardorder() {
        return this.partnerCardorder;
    }
    
    public void setPartnerCardorder(PartnerCardOrder partnerCardorder) {
        this.partnerCardorder = partnerCardorder;
    }

    public Long getNoofcards() {
        return this.noofcards;
    }
    
    public void setNoofcards(Long noofcards) {
        this.noofcards = noofcards;
    }

    public String getOrdervalue() {
        return this.ordervalue;
    }
    
    public void setOrdervalue(String ordervalue) {
        this.ordervalue = ordervalue;
    }

    public Double getCashvalue() {
        return this.cashvalue;
    }
    
    public void setCashvalue(Double cashvalue) {
        this.cashvalue = cashvalue;
    }

    public Double getShippingamount() {
        return this.shippingamount;
    }
    
    public void setShippingamount(Double shippingamount) {
        this.shippingamount = shippingamount;
    }

    public Date getShippeddate() {
        return this.shippeddate;
    }
    
    public void setShippeddate(Date shippeddate) {
        this.shippeddate = shippeddate;
    }

    public Long getNextfareorderid() {
        return this.nextfareorderid;
    }
    
    public void setNextfareorderid(Long nextfareorderid) {
        this.nextfareorderid = nextfareorderid;
    }

    public Long getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(Long batchid) {
        this.batchid = batchid;
    }

    public Set getBcwtpartnerproductdetailses() {
        return this.bcwtpartnerproductdetailses;
    }
    
    public void setBcwtpartnerproductdetailses(Set bcwtpartnerproductdetailses) {
        this.bcwtpartnerproductdetailses = bcwtpartnerproductdetailses;
    }
   








}