package com.marta.admin.hibernate;

import java.io.Serializable;
import java.util.Date;


/**
 * BcwtPartnerQualityResult generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerQualityResult  implements Serializable {

     private Long partnerqualityresultid;
     private PartnerCardOrder partnercardorder;
     private String qualityresult;
     private String note;
     private Date processed;
     private PartnerAdminDetails processedby;
     private String activestatus;

	/**
	 * @return the activestatus
	 */
	public String getActivestatus() {
		return activestatus;
	}
	/**
	 * @param activestatus the activestatus to set
	 */
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}
	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}
	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
	/**
	 * @return the partnercardorder
	 */
	public PartnerCardOrder getPartnercardorder() {
		return partnercardorder;
	}
	/**
	 * @param partnercardorder the partnercardorder to set
	 */
	public void setPartnercardorder(PartnerCardOrder partnercardorder) {
		this.partnercardorder = partnercardorder;
	}
	/**
	 * @return the partnerqualityresultid
	 */
	public Long getPartnerqualityresultid() {
		return partnerqualityresultid;
	}
	/**
	 * @param partnerqualityresultid the partnerqualityresultid to set
	 */
	public void setPartnerqualityresultid(Long partnerqualityresultid) {
		this.partnerqualityresultid = partnerqualityresultid;
	}
	/**
	 * @return the processed
	 */
	public Date getProcessed() {
		return processed;
	}
	/**
	 * @param processed the processed to set
	 */
	public void setProcessed(Date processed) {
		this.processed = processed;
	}	
	/**
	 * @return the processedby
	 */
	public PartnerAdminDetails getProcessedby() {
		return processedby;
	}
	/**
	 * @param processedby the processedby to set
	 */
	public void setProcessedby(PartnerAdminDetails processedby) {
		this.processedby = processedby;
	}
	/**
	 * @return the qualityresult
	 */
	public String getQualityresult() {
		return qualityresult;
	}
	/**
	 * @param qualityresult the qualityresult to set
	 */
	public void setQualityresult(String qualityresult) {
		this.qualityresult = qualityresult;
	}



}