package com.marta.admin.hibernate;

/**
 * Bcwtbarcode generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerBarCode  implements java.io.Serializable {

	private Long partnerbarcodeid;
	private Long orderid;
	private String barcode;

	/**
	 * @return the barcode
	 */
	public String getBarcode() {
		return barcode;
	}
	/**
	 * @param barcode the barcode to set
	 */
	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}
	/**
	 * @return the orderid
	 */
	public Long getOrderid() {
		return orderid;
	}
	/**
	 * @param orderid the orderid to set
	 */
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}
	/**
	 * @return the partnerbarcodeid
	 */
	public Long getPartnerbarcodeid() {
		return partnerbarcodeid;
	}
	/**
	 * @param partnerbarcodeid the partnerbarcodeid to set
	 */
	public void setPartnerbarcodeid(Long partnerbarcodeid) {
		this.partnerbarcodeid = partnerbarcodeid;
	}


}