package com.marta.admin.hibernate;



/**
 * BcwtProductAccntNums generated by MyEclipse - Hibernate Tools
 */

public class BcwtProductAccntNums  implements java.io.Serializable {


    // Fields    

     private BcwtProductAccntNumsId id;
     private Long chartOfAccountsId;
     private Long codeCombinationId;
     private Long salesAccnt;


    // Constructors

    public Long getSalesAccnt() {
		return salesAccnt;
	}


	public void setSalesAccnt(Long salesAccnt) {
		this.salesAccnt = salesAccnt;
	}


	/** default constructor */
    public BcwtProductAccntNums() {
    }

    
    /** full constructor */
    public BcwtProductAccntNums(BcwtProductAccntNumsId id) {
        this.id = id;
    }

   
    // Property accessors

    public BcwtProductAccntNumsId getId() {
        return this.id;
    }
    
    public void setId(BcwtProductAccntNumsId id) {
        this.id = id;
    }


	/**
	 * @return the chartOfAccountsId
	 */
	public Long getChartOfAccountsId() {
		return chartOfAccountsId;
	}


	/**
	 * @param chartOfAccountsId the chartOfAccountsId to set
	 */
	public void setChartOfAccountsId(Long chartOfAccountsId) {
		this.chartOfAccountsId = chartOfAccountsId;
	}


	/**
	 * @return the codeCombinationId
	 */
	public Long getCodeCombinationId() {
		return codeCombinationId;
	}


	/**
	 * @param codeCombinationId the codeCombinationId to set
	 */
	public void setCodeCombinationId(Long codeCombinationId) {
		this.codeCombinationId = codeCombinationId;
	}
   








}