package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtsecretquestions generated by MyEclipse - Hibernate Tools
 */

public class BcwtSecretQuestions  implements java.io.Serializable {


    // Fields

     private Long secretquestionid;
     private String secretquestion;
     private Set bcwtpwdverifiies = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtSecretQuestions() {
    }



    // Property accessors

    public Long getSecretquestionid() {
        return this.secretquestionid;
    }

    public void setSecretquestionid(Long secretquestionid) {
        this.secretquestionid = secretquestionid;
    }

    public String getSecretquestion() {
        return this.secretquestion;
    }

    public void setSecretquestion(String secretquestion) {
        this.secretquestion = secretquestion;
    }

    public Set getBcwtpwdverifiies() {
        return this.bcwtpwdverifiies;
    }

    public void setBcwtpwdverifiies(Set bcwtpwdverifiies) {
        this.bcwtpwdverifiies = bcwtpwdverifiies;
    }



	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((secretquestionid == null) ? 0 : secretquestionid.hashCode());
		return result;
	}



	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtSecretQuestions other = (BcwtSecretQuestions) obj;
		if (secretquestionid == null) {
			if (other.secretquestionid != null)
				return false;
		} else if (!secretquestionid.equals(other.secretquestionid))
			return false;
		return true;
	}



	
}