package com.marta.admin.hibernate;



/**
 * Bcwtorderdetails generated by MyEclipse - Hibernate Tools
 */

public class BcwtOrderDetails  implements java.io.Serializable {


    // Fields

     private Long orderdetailsid;
     private BcwtOrder bcwtorder;
     private BcwtPatronBreezeCard bcwtpatronbreezecard;
     private Double cashvalue;

    // Constructors

    public Double getCashvalue() {
		return cashvalue;
	}


	public void setCashvalue(Double cashvalue) {
		this.cashvalue = cashvalue;
	}


	/** default constructor */
    public BcwtOrderDetails() {
    }


    // Property accessors

    public Long getOrderdetailsid() {
        return this.orderdetailsid;
    }

    public void setOrderdetailsid(Long orderdetailsid) {
        this.orderdetailsid = orderdetailsid;
    }

    public BcwtOrder getBcwtorder() {
        return this.bcwtorder;
    }

    public void setBcwtorder(BcwtOrder bcwtorder) {
        this.bcwtorder = bcwtorder;
    }

    public BcwtPatronBreezeCard getBcwtpatronbreezecard() {
        return this.bcwtpatronbreezecard;
    }

    public void setBcwtpatronbreezecard(BcwtPatronBreezeCard bcwtpatronbreezecard) {
        this.bcwtpatronbreezecard = bcwtpatronbreezecard;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((orderdetailsid == null) ? 0 : orderdetailsid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtOrderDetails other = (BcwtOrderDetails) obj;
		if (orderdetailsid == null) {
			if (other.orderdetailsid != null)
				return false;
		} else if (!orderdetailsid.equals(other.orderdetailsid))
			return false;
		return true;
	}

}