package com.marta.admin.hibernate;

import java.io.Serializable;
import java.util.Date;


/**
 * Bcwtqualityresult generated by MyEclipse - Hibernate Tools
 */

public class BcwtQualityResult  implements Serializable {

     private Long qualityresultid;
     private BcwtPatron bcwtpatron;
     private BcwtOrder bcwtorder;
     private String qualityresult;
     private String note;
     private Date processeddate;
     private String activestatus;
     
	/**
	 * @return the activestatus
	 */
	public String getActivestatus() {
		return activestatus;
	}
	/**
	 * @param activestatus the activestatus to set
	 */
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}
	/**
	 * @return the bcwtorder
	 */
	public BcwtOrder getBcwtorder() {
		return bcwtorder;
	}
	/**
	 * @param bcwtorder the bcwtorder to set
	 */
	public void setBcwtorder(BcwtOrder bcwtorder) {
		this.bcwtorder = bcwtorder;
	}
	/**
	 * @return the bcwtpatron
	 */
	public BcwtPatron getBcwtpatron() {
		return bcwtpatron;
	}
	/**
	 * @param bcwtpatron the bcwtpatron to set
	 */
	public void setBcwtpatron(BcwtPatron bcwtpatron) {
		this.bcwtpatron = bcwtpatron;
	}
	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}
	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}
	/**
	 * @return the processeddate
	 */
	public Date getProcesseddate() {
		return processeddate;
	}
	/**
	 * @param processeddate the processeddate to set
	 */
	public void setProcesseddate(Date processeddate) {
		this.processeddate = processeddate;
	}
	/**
	 * @return the qualityresult
	 */
	public String getQualityresult() {
		return qualityresult;
	}
	/**
	 * @param qualityresult the qualityresult to set
	 */
	public void setQualityresult(String qualityresult) {
		this.qualityresult = qualityresult;
	}
	/**
	 * @return the qualityresultid
	 */
	public Long getQualityresultid() {
		return qualityresultid;
	}
	/**
	 * @param qualityresultid the qualityresultid to set
	 */
	public void setQualityresultid(Long qualityresultid) {
		this.qualityresultid = qualityresultid;
	}
     
}