package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtpatrontype generated by MyEclipse - Hibernate Tools
 */

public class BcwtPatronType  implements java.io.Serializable {


    // Fields

     private Long patrontypeid;
     private String patrontypename;
     private Set bcwtpatrontypemenuassociations = new HashSet(0);
     private Set bcwtpatrons = new HashSet(0);
     private Set bcwtuserrolepermission = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtPatronType() {
    }


    // Property accessors

    public Long getPatrontypeid() {
        return this.patrontypeid;
    }

    public void setPatrontypeid(Long patrontypeid) {
        this.patrontypeid = patrontypeid;
    }

    public String getPatrontypename() {
        return this.patrontypename;
    }

    public void setPatrontypename(String patrontypename) {
        this.patrontypename = patrontypename;
    }

    public Set getBcwtpatrontypemenuassociations() {
        return this.bcwtpatrontypemenuassociations;
    }

    public void setBcwtpatrontypemenuassociations(Set bcwtpatrontypemenuassociations) {
        this.bcwtpatrontypemenuassociations = bcwtpatrontypemenuassociations;
    }

    public Set getBcwtpatrons() {
        return this.bcwtpatrons;
    }

    public void setBcwtpatrons(Set bcwtpatrons) {
        this.bcwtpatrons = bcwtpatrons;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((patrontypeid == null) ? 0 : patrontypeid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtPatronType other = (BcwtPatronType) obj;
		if (patrontypeid == null) {
			if (other.patrontypeid != null)
				return false;
		} else if (!patrontypeid.equals(other.patrontypeid))
			return false;
		return true;
	}


	public Set getBcwtuserrolepermission() {
		return bcwtuserrolepermission;
	}


	public void setBcwtuserrolepermission(Set bcwtuserrolepermission) {
		this.bcwtuserrolepermission = bcwtuserrolepermission;
	}

}