package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwtbreezecardproduct generated by MyEclipse - Hibernate Tools
 */

public class BcwtBreezeCardProduct  implements java.io.Serializable {


    // Fields

     private Long breezecardproductid;
     private BcwtProduct bcwtproduct;
     private BcwtPatronBreezeCard bcwtpatronbreezecard;
     private String balancevalue;
     private Date expirydate;
     private String threshold;
     private Date recurring;
     private BcwtRegion bcwtregion;
     private BcwtOrderDetails bcwtorderdetails;
     private Double price;

    // Constructors

    /**
	 * @return the price
	 */
	public Double getPrice() {
		return price;
	}


	/**
	 * @param price the price to set
	 */
	public void setPrice(Double price) {
		this.price = price;
	}


	public BcwtOrderDetails getBcwtorderdetails() {
		return bcwtorderdetails;
	}


	public void setBcwtorderdetails(BcwtOrderDetails bcwtorderdetails) {
		this.bcwtorderdetails = bcwtorderdetails;
	}


	/** default constructor */
    public BcwtBreezeCardProduct() {
    }


    // Property accessors

    public Long getBreezecardproductid() {
        return this.breezecardproductid;
    }

    public void setBreezecardproductid(Long breezecardproductid) {
        this.breezecardproductid = breezecardproductid;
    }

    public BcwtProduct getBcwtproduct() {
        return this.bcwtproduct;
    }

    public void setBcwtproduct(BcwtProduct bcwtproduct) {
        this.bcwtproduct = bcwtproduct;
    }

    public BcwtPatronBreezeCard getBcwtpatronbreezecard() {
        return this.bcwtpatronbreezecard;
    }

    public void setBcwtpatronbreezecard(BcwtPatronBreezeCard bcwtpatronbreezecard) {
        this.bcwtpatronbreezecard = bcwtpatronbreezecard;
    }

    public String getBalancevalue() {
        return this.balancevalue;
    }

    public void setBalancevalue(String balancevalue) {
        this.balancevalue = balancevalue;
    }

    public Date getExpirydate() {
        return this.expirydate;
    }

    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    public String getThreshold() {
        return this.threshold;
    }

    public void setThreshold(String threshold) {
        this.threshold = threshold;
    }

    public Date getRecurring() {
        return this.recurring;
    }

    public void setRecurring(Date recurring) {
        this.recurring = recurring;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((breezecardproductid == null) ? 0 : breezecardproductid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtBreezeCardProduct other = (BcwtBreezeCardProduct) obj;
		if (breezecardproductid == null) {
			if (other.breezecardproductid != null)
				return false;
		} else if (!breezecardproductid.equals(other.breezecardproductid))
			return false;
		return true;
	}


	public BcwtRegion getBcwtregion() {
		return bcwtregion;
	}


	public void setBcwtregion(BcwtRegion bcwtregion) {
		this.bcwtregion = bcwtregion;
	}


	
	

}