package com.marta.admin.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bcwtpatronpaymentcards generated by MyEclipse - Hibernate Tools
 */

public class BcwtPatronPaymentCards  implements java.io.Serializable {

    // Fields    

     private Long patronpaymentcardid;
     private BcwtPatron bcwtpatron;
     private BcwtPatronAddress bcwtpatronaddress;
     private String nickname;
     private BcwtCreditCardType bcwtcreditcardtype;
     private Long paymentmode;
     private String creditcardno;
     private String nameoncard;
     private Date expirydate;
     private String activestatus;
     private String negativeliststatus;
     private String expirymonth;
     private String expiryyear;
     private Date transactiondate;
     private Set bcwtorders = new HashSet(0);
     private Set bcwtproductrecurring = new HashSet(0);
     private Set bcwtcashrecurring = new HashSet(0);
    // Constructors

    /** default constructor */
    public BcwtPatronPaymentCards() {
    }
   
    // Property accessors

    public Long getPatronpaymentcardid() {
        return this.patronpaymentcardid;
    }
    
    public void setPatronpaymentcardid(Long patronpaymentcardid) {
        this.patronpaymentcardid = patronpaymentcardid;
    }

    public BcwtPatron getBcwtpatron() {
        return this.bcwtpatron;
    }
    
    public void setBcwtpatron(BcwtPatron bcwtpatron) {
        this.bcwtpatron = bcwtpatron;
    }

   
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Long getPaymentmode() {
		return paymentmode;
	}

	public void setPaymentmode(Long paymentmode) {
		this.paymentmode = paymentmode;
	}

	public String getCreditcardno() {
        return this.creditcardno;
    }
    
    public void setCreditcardno(String creditcardno) {
        this.creditcardno = creditcardno;
    }

    public String getNameoncard() {
        return this.nameoncard;
    }
    
    public void setNameoncard(String nameoncard) {
        this.nameoncard = nameoncard;
    }

    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }

    public String getExpirymonth() {
        return this.expirymonth;
    }
    
    public void setExpirymonth(String expirymonth) {
        this.expirymonth = expirymonth;
    }

    public String getExpiryyear() {
        return this.expiryyear;
    }
    
    public void setExpiryyear(String expiryyear) {
        this.expiryyear = expiryyear;
    }

    public Set getBcwtorders() {
        return this.bcwtorders;
    }
    
    public void setBcwtorders(Set bcwtorders) {
        this.bcwtorders = bcwtorders;
    }

	/**
	 * @return the bcwtpatronaddress
	 */
	public BcwtPatronAddress getBcwtpatronaddress() {
		return bcwtpatronaddress;
	}

	/**
	 * @param bcwtpatronaddress the bcwtpatronaddress to set
	 */
	public void setBcwtpatronaddress(BcwtPatronAddress bcwtpatronaddress) {
		this.bcwtpatronaddress = bcwtpatronaddress;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((patronpaymentcardid == null) ? 0 : patronpaymentcardid.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtPatronPaymentCards other = (BcwtPatronPaymentCards) obj;
		if (patronpaymentcardid == null) {
			if (other.patronpaymentcardid != null)
				return false;
		} else if (!patronpaymentcardid.equals(other.patronpaymentcardid))
			return false;
		return true;
	}

	public Set getBcwtproductrecurring() {
		return bcwtproductrecurring;
	}

	public void setBcwtproductrecurring(Set bcwtproductrecurring) {
		this.bcwtproductrecurring = bcwtproductrecurring;
	}

	public Set getBcwtcashrecurring() {
		return bcwtcashrecurring;
	}

	public void setBcwtcashrecurring(Set bcwtcashrecurring) {
		this.bcwtcashrecurring = bcwtcashrecurring;
	}

	public BcwtCreditCardType getBcwtcreditcardtype() {
		return bcwtcreditcardtype;
	}

	public void setBcwtcreditcardtype(BcwtCreditCardType bcwtcreditcardtype) {
		this.bcwtcreditcardtype = bcwtcreditcardtype;
	}

	public String getNegativeliststatus() {
		return negativeliststatus;
	}

	public void setNegativeliststatus(String negativeliststatus) {
		this.negativeliststatus = negativeliststatus;
	}

	/**
	 * @return the transactiondate
	 */
	public Date getTransactiondate() {
		return transactiondate;
	}

	/**
	 * @param transactiondate the transactiondate to set
	 */
	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}
   
}