package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwtproductrecurring generated by MyEclipse - Hibernate Tools
 */

public class BcwtProductRecurring  implements java.io.Serializable {


    // Fields

     private Long productrecurringid;
     private BcwtPatronBreezeCard bcwtpatronbreezecard;
     private Long productid;
     private String recurringfrequency;
     private String recurringdayofweek;
     private String recurringdayofmonth;
     private Date dateproductadded;
     private String prodrecuringstatus;
     private String activestatus;
     private Long orderid;
     private BcwtPatronPaymentCards bcwtpatronpaymentcards;
     private Date lastrundate;
     private Date nextrundate;
    // Constructors

    /** default constructor */
    public BcwtProductRecurring() {
    }


    // Property accessors

    public Long getProductrecurringid() {
        return this.productrecurringid;
    }

    public void setProductrecurringid(Long productrecurringid) {
        this.productrecurringid = productrecurringid;
    }

    public BcwtPatronBreezeCard getBcwtpatronbreezecard() {
        return this.bcwtpatronbreezecard;
    }

    public void setBcwtpatronbreezecard(BcwtPatronBreezeCard bcwtpatronbreezecard) {
        this.bcwtpatronbreezecard = bcwtpatronbreezecard;
    }

    public Long getProductid() {
        return this.productid;
    }

    public void setProductid(Long productid) {
        this.productid = productid;
    }

    public String getRecurringfrequency() {
        return this.recurringfrequency;
    }

    public void setRecurringfrequency(String recurringfrequency) {
        this.recurringfrequency = recurringfrequency;
    }

    public String getRecurringdayofweek() {
        return this.recurringdayofweek;
    }

    public void setRecurringdayofweek(String recurringdayofweek) {
        this.recurringdayofweek = recurringdayofweek;
    }

    public String getRecurringdayofmonth() {
        return this.recurringdayofmonth;
    }

    public void setRecurringdayofmonth(String recurringdayofmonth) {
        this.recurringdayofmonth = recurringdayofmonth;
    }

    public Date getDateproductadded() {
        return this.dateproductadded;
    }

    public void setDateproductadded(Date dateproductadded) {
        this.dateproductadded = dateproductadded;
    }

	
	public String getActivestatus() {
		return activestatus;
	}


	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}


	public Long getOrderid() {
		return orderid;
	}


	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}


	public String getProdrecuringstatus() {
		return prodrecuringstatus;
	}


	public void setProdrecuringstatus(String prodrecuringstatus) {
		this.prodrecuringstatus = prodrecuringstatus;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	

	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((productrecurringid == null) ? 0 : productrecurringid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtProductRecurring other = (BcwtProductRecurring) obj;
		if (productrecurringid == null) {
			if (other.productrecurringid != null)
				return false;
		} else if (!productrecurringid.equals(other.productrecurringid))
			return false;
		return true;
	}


	public BcwtPatronPaymentCards getBcwtpatronpaymentcards() {
		return bcwtpatronpaymentcards;
	}


	public void setBcwtpatronpaymentcards(
			BcwtPatronPaymentCards bcwtpatronpaymentcards) {
		this.bcwtpatronpaymentcards = bcwtpatronpaymentcards;
	}


	public Date getLastrundate() {
		return lastrundate;
	}


	public void setLastrundate(Date lastrundate) {
		this.lastrundate = lastrundate;
	}


	public Date getNextrundate() {
		return nextrundate;
	}


	public void setNextrundate(Date nextrundate) {
		this.nextrundate = nextrundate;
	}

}