package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtpatronbreezecard generated by MyEclipse - Hibernate Tools
 */

public class BcwtPatronBreezeCard  implements java.io.Serializable {


    // Fields

     private Long breezecardid;
     private BcwtPatron bcwtpatron;
     private String breezecardname;
     private String breezecardserialnumber;
     private Double cashvalue;
     private Long thresholdvalue;
     private Double addcashvalue;
     private Set bcwtcashrecurrings = new HashSet(0);
     private Set bcwtproductrecurrings = new HashSet(0);
     private Set bcwtorderdetailses = new HashSet(0);
     private Set bcwtbreezecardproducts = new HashSet(0);
     private String activestatus;
     private String breezecardactivestatus;

    // Constructors

   


	/** default constructor */
    public BcwtPatronBreezeCard() {
    }


    // Property accessors

    public Long getBreezecardid() {
        return this.breezecardid;
    }

    public void setBreezecardid(Long breezecardid) {
        this.breezecardid = breezecardid;
    }

    public BcwtPatron getBcwtpatron() {
        return this.bcwtpatron;
    }

    public void setBcwtpatron(BcwtPatron bcwtpatron) {
        this.bcwtpatron = bcwtpatron;
    }

    public String getBreezecardname() {
        return this.breezecardname;
    }

    public void setBreezecardname(String breezecardname) {
        this.breezecardname = breezecardname;
    }
   
    public Double getCashvalue() {
        return this.cashvalue;
    }

    public void setCashvalue(Double cashvalue) {
        this.cashvalue = cashvalue;
    }

    public Long getThresholdvalue() {
        return this.thresholdvalue;
    }

    public void setThresholdvalue(Long thresholdvalue) {
        this.thresholdvalue = thresholdvalue;
    }

    public Double getAddcashvalue() {
        return this.addcashvalue;
    }

    public void setAddcashvalue(Double addcashvalue) {
        this.addcashvalue = addcashvalue;
    }

    public Set getBcwtcashrecurrings() {
        return this.bcwtcashrecurrings;
    }

    public void setBcwtcashrecurrings(Set bcwtcashrecurrings) {
        this.bcwtcashrecurrings = bcwtcashrecurrings;
    }

    public Set getBcwtproductrecurrings() {
        return this.bcwtproductrecurrings;
    }

    public void setBcwtproductrecurrings(Set bcwtproductrecurrings) {
        this.bcwtproductrecurrings = bcwtproductrecurrings;
    }

    public Set getBcwtorderdetailses() {
        return this.bcwtorderdetailses;
    }

    public void setBcwtorderdetailses(Set bcwtorderdetailses) {
        this.bcwtorderdetailses = bcwtorderdetailses;
    }

    public Set getBcwtbreezecardproducts() {
        return this.bcwtbreezecardproducts;
    }

    public void setBcwtbreezecardproducts(Set bcwtbreezecardproducts) {
        this.bcwtbreezecardproducts = bcwtbreezecardproducts;
    }
    
    
    
    public String getBreezecardserialnumber() {
		return breezecardserialnumber;
	}


	public void setBreezecardserialnumber(String breezecardserialnumber) {
		this.breezecardserialnumber = breezecardserialnumber;
	}


	/**
	 * @return the activestatus
	 */
	public String getActivestatus() {
		return activestatus;
	}


	/**
	 * @param activestatus the activestatus to set
	 */
	public void setActivestatus(String activestatus) {
		this.activestatus = activestatus;
	}


	/**
	 * @return the breezecardactivestatus
	 */
	public String getBreezecardactivestatus() {
		return breezecardactivestatus;
	}


	/**
	 * @param breezecardactivestatus the breezecardactivestatus to set
	 */
	public void setBreezecardactivestatus(String breezecardactivestatus) {
		this.breezecardactivestatus = breezecardactivestatus;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((breezecardid == null) ? 0 : breezecardid.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtPatronBreezeCard other = (BcwtPatronBreezeCard) obj;
		if (breezecardid == null) {
			if (other.breezecardid != null)
				return false;
		} else if (!breezecardid.equals(other.breezecardid))
			return false;
		return true;
	}

}