package com.marta.admin.hibernate;

import java.util.Date;
// Generated by MyEclipse - Hibernate Tools



/**
 * Bcwtlogcall generated by MyEclipse - Hibernate Tools
 */
public class BcwtLogCall  implements java.io.Serializable {

	private Long logcallid;
    private BcwtPatronType bcwtpatrontype;
    private Long patronid;
    private Date calldate;
    private Date calltime;
    private String adminemailid;
    private String adminphonenumber;
    private String adminname;
    private String reason;
    private String notes;
    private Long adminpatrontypeid;
    private Long adminpatronid;
    private String uploadedfilename;
    private String savedfilename;

   

  
   // Property accessors

   public Long getLogcallid() {
       return this.logcallid;
   }
   
   public void setLogcallid(Long logcallid) {
       this.logcallid = logcallid;
   }

  

   public BcwtPatronType getBcwtpatrontype() {
	return bcwtpatrontype;
}

public void setBcwtpatrontype(BcwtPatronType bcwtpatrontype) {
	this.bcwtpatrontype = bcwtpatrontype;
}

public Long getPatronid() {
       return this.patronid;
   }
   
   public void setPatronid(Long patronid) {
       this.patronid = patronid;
   }

   public Date getCalldate() {
       return this.calldate;
   }
   
   public void setCalldate(Date calldate) {
       this.calldate = calldate;
   }

   public Date getCalltime() {
       return this.calltime;
   }
   
   public void setCalltime(Date calltime) {
       this.calltime = calltime;
   }

   public String getAdminemailid() {
       return this.adminemailid;
   }
   
   public void setAdminemailid(String adminemailid) {
       this.adminemailid = adminemailid;
   }

   public String getAdminphonenumber() {
       return this.adminphonenumber;
   }
   
   public void setAdminphonenumber(String adminphonenumber) {
       this.adminphonenumber = adminphonenumber;
   }

   public String getAdminname() {
       return this.adminname;
   }
   
   public void setAdminname(String adminname) {
       this.adminname = adminname;
   }

   public String getReason() {
       return this.reason;
   }
   
   public void setReason(String reason) {
       this.reason = reason;
   }

   public String getNotes() {
       return this.notes;
   }
   
   public void setNotes(String notes) {
       this.notes = notes;
   }

public Long getAdminpatronid() {
	return adminpatronid;
}

public void setAdminpatronid(Long adminpatronid) {
	this.adminpatronid = adminpatronid;
}

public Long getAdminpatrontypeid() {
	return adminpatrontypeid;
}

public void setAdminpatrontypeid(Long adminpatrontypeid) {
	this.adminpatrontypeid = adminpatrontypeid;
}

/**
 * @return the savedfilename
 */
public String getSavedfilename() {
	return savedfilename;
}

/**
 * @param savedfilename the savedfilename to set
 */
public void setSavedfilename(String savedfilename) {
	this.savedfilename = savedfilename;
}

/**
 * @return the uploadedfilename
 */
public String getUploadedfilename() {
	return uploadedfilename;
}

/**
 * @param uploadedfilename the uploadedfilename to set
 */
public void setUploadedfilename(String uploadedfilename) {
	this.uploadedfilename = uploadedfilename;
}   
}
