package com.marta.admin.hibernate;



/**
 * Bcwtpartnerproduct generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerProduct  implements java.io.Serializable {


    // Fields    

     private Long productid;
     private BcwtRegion bcwtregion;
     private Long fareInstrumentId;
     private Long companytypeid;
     private String productname;
     private String productdescription;
     private String productdetaildesc;
     private Long riderclassification;
     private String price;
     private Long sortorder;


    // Constructors

    /** default constructor */
    public BcwtPartnerProduct() {
    }

	/** minimal constructor */
    public BcwtPartnerProduct(BcwtRegion bcwtregion, Long fareInstrumentId, Long companytypeid) {
        this.bcwtregion = bcwtregion;
        this.fareInstrumentId = fareInstrumentId;
        this.companytypeid = companytypeid;
    }
    
    /** full constructor */
    public BcwtPartnerProduct(BcwtRegion bcwtregion, Long fareInstrumentId, Long companytypeid, String productname, String productdescription, String productdetaildesc, Long riderclassification, String price, Long sortorder) {
        this.bcwtregion = bcwtregion;
        this.fareInstrumentId = fareInstrumentId;
        this.companytypeid = companytypeid;
        this.productname = productname;
        this.productdescription = productdescription;
        this.productdetaildesc = productdetaildesc;
        this.riderclassification = riderclassification;
        this.price = price;
        this.sortorder = sortorder;
    }

   
    // Property accessors

    public Long getProductid() {
        return this.productid;
    }
    
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    public BcwtRegion getBcwtregion() {
        return this.bcwtregion;
    }
    
    public void setBcwtregion(BcwtRegion bcwtregion) {
        this.bcwtregion = bcwtregion;
    }

    public Long getFareInstrumentId() {
        return this.fareInstrumentId;
    }
    
    public void setFareInstrumentId(Long fareInstrumentId) {
        this.fareInstrumentId = fareInstrumentId;
    }

    public Long getCompanytypeid() {
        return this.companytypeid;
    }
    
    public void setCompanytypeid(Long companytypeid) {
        this.companytypeid = companytypeid;
    }

    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getProductdescription() {
        return this.productdescription;
    }
    
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    public String getProductdetaildesc() {
        return this.productdetaildesc;
    }
    
    public void setProductdetaildesc(String productdetaildesc) {
        this.productdetaildesc = productdetaildesc;
    }

    public Long getRiderclassification() {
        return this.riderclassification;
    }
    
    public void setRiderclassification(Long riderclassification) {
        this.riderclassification = riderclassification;
    }

    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    public Long getSortorder() {
        return this.sortorder;
    }
    
    public void setSortorder(Long sortorder) {
        this.sortorder = sortorder;
    }
   








}