package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtshipmentmethods generated by MyEclipse - Hibernate Tools
 */

public class BcwtShipmentmethods  implements java.io.Serializable {


    // Fields    

     private Long shipmentmethodid;
     private String shipmentprovider;
     private String shipmentmethod;
     private Long cardcount;
     private Double shipmentprice;
     private String activestatus;
     private String shipmenttrackurl;
     private Set bcwtorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtShipmentmethods() {
    }

    
    /** full constructor */
    public BcwtShipmentmethods(String shipmentprovider, String shipmentmethod, Long cardcount, Double shipmentprice, String activestatus, String shipmenttrackurl, Set bcwtorders) {
        this.shipmentprovider = shipmentprovider;
        this.shipmentmethod = shipmentmethod;
        this.cardcount = cardcount;
        this.shipmentprice = shipmentprice;
        this.activestatus = activestatus;
        this.shipmenttrackurl = shipmenttrackurl;
        this.bcwtorders = bcwtorders;
    }

   
    // Property accessors

    public Long getShipmentmethodid() {
        return this.shipmentmethodid;
    }
    
    public void setShipmentmethodid(Long shipmentmethodid) {
        this.shipmentmethodid = shipmentmethodid;
    }

    public String getShipmentprovider() {
        return this.shipmentprovider;
    }
    
    public void setShipmentprovider(String shipmentprovider) {
        this.shipmentprovider = shipmentprovider;
    }

    public String getShipmentmethod() {
        return this.shipmentmethod;
    }
    
    public void setShipmentmethod(String shipmentmethod) {
        this.shipmentmethod = shipmentmethod;
    }

    public Long getCardcount() {
        return this.cardcount;
    }
    
    public void setCardcount(Long cardcount) {
        this.cardcount = cardcount;
    }

    public Double getShipmentprice() {
        return this.shipmentprice;
    }
    
    public void setShipmentprice(Double shipmentprice) {
        this.shipmentprice = shipmentprice;
    }

    public String getActivestatus() {
        return this.activestatus;
    }
    
    public void setActivestatus(String activestatus) {
        this.activestatus = activestatus;
    }

    public String getShipmenttrackurl() {
        return this.shipmenttrackurl;
    }
    
    public void setShipmenttrackurl(String shipmenttrackurl) {
        this.shipmenttrackurl = shipmenttrackurl;
    }

    public Set getBcwtorders() {
        return this.bcwtorders;
    }
    
    public void setBcwtorders(Set bcwtorders) {
        this.bcwtorders = bcwtorders;
    }
   








}