package com.marta.admin.hibernate;



/**
 * Bcwtpatrontypemenuassociation generated by MyEclipse - Hibernate Tools
 */

public class BcwtPatronTypeMenuAssociation  implements java.io.Serializable {


    // Fields

     private Long patrontypeassociationid;
     private BcwtMenuMaster bcwtmenumaster;
     private BcwtPatronType bcwtpatrontype;


    // Constructors

    /** default constructor */
    public BcwtPatronTypeMenuAssociation() {
    }



    // Property accessors

    public Long getPatrontypeassociationid() {
        return this.patrontypeassociationid;
    }

    public void setPatrontypeassociationid(Long patrontypeassociationid) {
        this.patrontypeassociationid = patrontypeassociationid;
    }

    public BcwtMenuMaster getBcwtmenumaster() {
        return this.bcwtmenumaster;
    }

    public void setBcwtmenumaster(BcwtMenuMaster bcwtmenumaster) {
        this.bcwtmenumaster = bcwtmenumaster;
    }

    public BcwtPatronType getBcwtpatrontype() {
        return this.bcwtpatrontype;
    }

    public void setBcwtpatrontype(BcwtPatronType bcwtpatrontype) {
        this.bcwtpatrontype = bcwtpatrontype;
    }



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */

	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((patrontypeassociationid == null) ? 0 : patrontypeassociationid.hashCode());
		return result;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtPatronTypeMenuAssociation other = (BcwtPatronTypeMenuAssociation) obj;
		if (patrontypeassociationid == null) {
			if (other.patrontypeassociationid != null)
				return false;
		} else if (!patrontypeassociationid.equals(other.patrontypeassociationid))
			return false;
		return true;
	}

}