package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtorderstatus generated by MyEclipse - Hibernate Tools
 */

public class BcwtOrderStatus  implements java.io.Serializable {


    // Fields

     private Long orderstatusid;
     private String orderstatusname;
     private String displayinhistory;
     private Set bcwtorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtOrderStatus() {
    }



    // Property accessors

    public Long getOrderstatusid() {
        return this.orderstatusid;
    }

    public void setOrderstatusid(Long orderstatusid) {
        this.orderstatusid = orderstatusid;
    }

    public String getOrderstatusname() {
        return this.orderstatusname;
    }

    public void setOrderstatusname(String orderstatusname) {
        this.orderstatusname = orderstatusname;
    }

    public Set getBcwtorders() {
        return this.bcwtorders;
    }

    public void setBcwtorders(Set bcwtorders) {
        this.bcwtorders = bcwtorders;
    }



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((orderstatusid == null) ? 0 : orderstatusid.hashCode());
		return result;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtOrderStatus other = (BcwtOrderStatus) obj;
		if (orderstatusid == null) {
			if (other.orderstatusid != null)
				return false;
		} else if (!orderstatusid.equals(other.orderstatusid))
			return false;
		return true;
	}



	public String getDisplayinhistory() {
		return displayinhistory;
	}



	public void setDisplayinhistory(String displayinhistory) {
		this.displayinhistory = displayinhistory;
	}

}