package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Bcwtstate generated by MyEclipse - Hibernate Tools
 */

public class BcwtState  implements java.io.Serializable {


    // Fields

     private Long stateid;
     private String statename;
     private String statecode;
     private Set bcwtpatronaddresses = new HashSet(0);


    // Constructors

    /** default constructor */
    public BcwtState() {
    }



    // Property accessors

    public Long getStateid() {
        return this.stateid;
    }

    public void setStateid(Long stateid) {
        this.stateid = stateid;
    }

    public String getStatename() {
        return this.statename;
    }

    public void setStatename(String statename) {
        this.statename = statename;
    }

    public Set getBcwtpatronaddresses() {
        return this.bcwtpatronaddresses;
    }

    public void setBcwtpatronaddresses(Set bcwtpatronaddresses) {
        this.bcwtpatronaddresses = bcwtpatronaddresses;
    }



	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((stateid == null) ? 0 : stateid.hashCode());
		return result;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BcwtState other = (BcwtState) obj;
		if (stateid == null) {
			if (other.stateid != null)
				return false;
		} else if (!stateid.equals(other.stateid))
			return false;
		return true;
	}



	public String getStatecode() {
		return statecode;
	}



	public void setStatecode(String statecode) {
		this.statecode = statecode;
	}


}