package com.marta.admin.hibernate;

import java.util.Date;



/**
 * Bcwtpartnernewcard generated by MyEclipse - Hibernate Tools
 */

public class BcwtPartnerNewCard  implements java.io.Serializable {


    // Fields    

     private Long partnernewcardid;
     private Long memberid;
     private String serialnumber;
     private String firstname;
     private String lastname;
     private String email;
     private String phoneno;
     private Long benefitid;
     private Long benefitid2;
     private Long benefitid3;
     private Long benefitid4;
     private String customermemberid;
     
     private Long companyid;
     private String companyname;
     private Date date_added;

    // Constructors

     
     
     
     
    /**
	 * @return the companyid
	 */
	public Long getCompanyid() {
		return companyid;
	}


	public Date getDate_added() {
		return date_added;
	}


	public void setDate_added(Date date_added) {
		this.date_added = date_added;
	}


	public Long getBenefitid2() {
		return benefitid2;
	}


	public void setBenefitid2(Long benefitid2) {
		this.benefitid2 = benefitid2;
	}


	public Long getBenefitid3() {
		return benefitid3;
	}


	public void setBenefitid3(Long benefitid3) {
		this.benefitid3 = benefitid3;
	}


	public Long getBenefitid4() {
		return benefitid4;
	}


	public void setBenefitid4(Long benefitid4) {
		this.benefitid4 = benefitid4;
	}


	/**
	 * @param companyid the companyid to set
	 */
	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}


	/**
	 * @return the companyname
	 */
	public String getCompanyname() {
		return companyname;
	}


	/**
	 * @param companyname the companyname to set
	 */
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}


	public String getCustomermemberid() {
		return customermemberid;
	}


	public void setCustomermemberid(String customermemberid) {
		this.customermemberid = customermemberid;
	}


	/** default constructor */
    public BcwtPartnerNewCard() {
    }

    
    /** full constructor */
    public BcwtPartnerNewCard(Long memberid, String serialnumber, String firstname, String lastname, String email, String phoneno, Long benefitid) {
        this.memberid = memberid;
        this.serialnumber = serialnumber;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.phoneno = phoneno;
        this.benefitid = benefitid;
    }

   
    // Property accessors

    public Long getPartnernewcardid() {
        return this.partnernewcardid;
    }
    
    public void setPartnernewcardid(Long partnernewcardid) {
        this.partnernewcardid = partnernewcardid;
    }

    public Long getMemberid() {
        return this.memberid;
    }
    
    public void setMemberid(Long memberid) {
        this.memberid = memberid;
    }

    public String getSerialnumber() {
        return this.serialnumber;
    }
    
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
    }

    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    public Long getBenefitid() {
        return this.benefitid;
    }
    
    public void setBenefitid(Long benefitid) {
        this.benefitid = benefitid;
    }
   








}