package com.marta.admin.hibernate;

import java.util.Date;


/**
 * Bcwthotlistcarddetails generated by MyEclipse - Hibernate Tools
 */

public class BcwtHotListCardDetails  implements java.io.Serializable {


    // Fields    

     private Long hotlistcarddetailsid;
     private PartnerCompanyInfo partnerCompanyinfo;
     private PartnerAdminDetails partnerAdmindetails;
     private String companyname;
     private Long memberid;
     private String serialnumber;
     private String firstname;
     private String lastname;
     private Date hotlisteddate;
     private String customermemberid;
     
     //Changes given by Ubaid
     private String pointofsale;
     private String adminname;


    // Constructors

    /**
	 * @return the adminname
	 */
	public String getAdminname() {
		return adminname;
	}


	/**
	 * @param adminname the adminname to set
	 */
	public void setAdminname(String adminname) {
		this.adminname = adminname;
	}


	/**
	 * @return the pointofsale
	 */
	public String getPointofsale() {
		return pointofsale;
	}


	/**
	 * @param pointofsale the pointofsale to set
	 */
	public void setPointofsale(String pointofsale) {
		this.pointofsale = pointofsale;
	}


	/** default constructor */
    public BcwtHotListCardDetails() {
    }


	public String getCompanyname() {
		return companyname;
	}


	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}


	public String getFirstname() {
		return firstname;
	}


	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}


	public Long getHotlistcarddetailsid() {
		return hotlistcarddetailsid;
	}


	public void setHotlistcarddetailsid(Long hotlistcarddetailsid) {
		this.hotlistcarddetailsid = hotlistcarddetailsid;
	}


	public Date getHotlisteddate() {
		return hotlisteddate;
	}


	public void setHotlisteddate(Date hotlisteddate) {
		this.hotlisteddate = hotlisteddate;
	}


	public String getLastname() {
		return lastname;
	}


	public void setLastname(String lastname) {
		this.lastname = lastname;
	}


	public Long getMemberid() {
		return memberid;
	}


	public void setMemberid(Long memberid) {
		this.memberid = memberid;
	}


	public PartnerAdminDetails getPartnerAdmindetails() {
		return partnerAdmindetails;
	}


	public void setPartnerAdmindetails(PartnerAdminDetails partnerAdmindetails) {
		this.partnerAdmindetails = partnerAdmindetails;
	}


	public PartnerCompanyInfo getPartnerCompanyinfo() {
		return partnerCompanyinfo;
	}


	public void setPartnerCompanyinfo(PartnerCompanyInfo partnerCompanyinfo) {
		this.partnerCompanyinfo = partnerCompanyinfo;
	}


	public String getSerialnumber() {
		return serialnumber;
	}


	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}


	public String getCustomermemberid() {
		return customermemberid;
	}


	public void setCustomermemberid(String customermemberid) {
		this.customermemberid = customermemberid;
	}

	
   








}