package com.marta.admin.hibernate;



/**
 * PartnerTransactionbenefits generated by MyEclipse - Hibernate Tools
 */

public class PartnerTransactionBenefits  implements java.io.Serializable {


    // Fields    

     private Long transactionId;
     private Long partnerId;
     private Long cardSerialNo;
     private String benefitId;
     private String benefitActionId;
     private String nfsBenefitId;
     private String benefitType;


    // Constructors

    /** default constructor */
    public PartnerTransactionBenefits() {
    }

    
    /** full constructor */
    public PartnerTransactionBenefits(Long partnerId, Long cardSerialNo, String benefitId, String benefitActionId, String nfsBenefitId, String benefitType) {
        this.partnerId = partnerId;
        this.cardSerialNo = cardSerialNo;
        this.benefitId = benefitId;
        this.benefitActionId = benefitActionId;
        this.nfsBenefitId = nfsBenefitId;
        this.benefitType = benefitType;
    }

   
    // Property accessors

    public Long getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    public Long getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    public Long getCardSerialNo() {
        return this.cardSerialNo;
    }
    
    public void setCardSerialNo(Long cardSerialNo) {
        this.cardSerialNo = cardSerialNo;
    }

    public String getBenefitId() {
        return this.benefitId;
    }
    
    public void setBenefitId(String benefitId) {
        this.benefitId = benefitId;
    }

    public String getBenefitActionId() {
        return this.benefitActionId;
    }
    
    public void setBenefitActionId(String benefitActionId) {
        this.benefitActionId = benefitActionId;
    }

    public String getNfsBenefitId() {
        return this.nfsBenefitId;
    }
    
    public void setNfsBenefitId(String nfsBenefitId) {
        this.nfsBenefitId = nfsBenefitId;
    }

    public String getBenefitType() {
        return this.benefitType;
    }
    
    public void setBenefitType(String benefitType) {
        this.benefitType = benefitType;
    }
   








}