package com.marta.admin.hibernate;



/**
 * PartnerRoleaccess generated by MyEclipse - Hibernate Tools
 */

public class PartnerRoleAccess  implements java.io.Serializable {


    // Fields    

     private Long roleid;
     private PartnerWebResources partnerWebResources;
     private String isaccessible;


    // Constructors

    /** default constructor */
    public PartnerRoleAccess() {
    }

    
    /** full constructor */
    public PartnerRoleAccess(PartnerWebResources partnerWebResources, String isaccessible) {
        this.partnerWebResources = partnerWebResources;
        this.isaccessible = isaccessible;
    }

   
    // Property accessors

    public Long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    public PartnerWebResources getPartnerWebresources() {
        return this.partnerWebResources;
    }
    
    public void setPartnerWebresources(PartnerWebResources partnerWebResources) {
        this.partnerWebResources = partnerWebResources;
    }

    public String getIsaccessible() {
        return this.isaccessible;
    }
    
    public void setIsaccessible(String isaccessible) {
        this.isaccessible = isaccessible;
    }
   








}