package com.marta.admin.hibernate;



/**
 * PartnerOrdershipmentId generated by MyEclipse - Hibernate Tools
 */

public class PartnerOrderShipmentId  implements java.io.Serializable {


    // Fields    

     private Long shipmentId;
     private String tackingNo;


    // Constructors

    /** default constructor */
    public PartnerOrderShipmentId() {
    }

    
    /** full constructor */
    public PartnerOrderShipmentId(Long shipmentId, String tackingNo) {
        this.shipmentId = shipmentId;
        this.tackingNo = tackingNo;
    }

   
    // Property accessors

    public Long getShipmentId() {
        return this.shipmentId;
    }
    
    public void setShipmentId(Long shipmentId) {
        this.shipmentId = shipmentId;
    }

    public String getTackingNo() {
        return this.tackingNo;
    }
    
    public void setTackingNo(String tackingNo) {
        this.tackingNo = tackingNo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartnerOrderShipmentId) ) return false;
		 PartnerOrderShipmentId castOther = ( PartnerOrderShipmentId ) other; 
         
		 return ( (this.getShipmentId()==castOther.getShipmentId()) || ( this.getShipmentId()!=null && castOther.getShipmentId()!=null && this.getShipmentId().equals(castOther.getShipmentId()) ) )
 && ( (this.getTackingNo()==castOther.getTackingNo()) || ( this.getTackingNo()!=null && castOther.getTackingNo()!=null && this.getTackingNo().equals(castOther.getTackingNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getShipmentId() == null ? 0 : this.getShipmentId().hashCode() );
         result = 37 * result + ( getTackingNo() == null ? 0 : this.getTackingNo().hashCode() );
         return result;
   }   





}