package com.marta.admin.hibernate;

import java.util.Date;


/**
 * PartnerCardorder generated by MyEclipse - Hibernate Tools
 */

public class PartnerCardOrder  implements java.io.Serializable {


    // Fields    

     private Long orderId;
     private PartnerCardOrderStatus partnerCardorderstatus;
     private PartnerAddress partnerAddress;
     private PartnerAdminDetails partnerAdmindetails;
     private PartnerCompanyInfo partnerCompanyinfo;
     private Long orderQty;
     private Date orderDate;
     private String contactName;
     private String notes;
     private Long shipmentId;
     private PartnerAdminDetails processedBy;


    // Constructors

    /**
	 * @return the processedBy
	 */
	public PartnerAdminDetails getProcessedBy() {
		return processedBy;
	}

	/**
	 * @param processedBy the processedBy to set
	 */
	public void setProcessedBy(PartnerAdminDetails processedBy) {
		this.processedBy = processedBy;
	}

	/** default constructor */
    public PartnerCardOrder() {
    }

	/** minimal constructor */
    public PartnerCardOrder(PartnerAddress partnerAddress, PartnerAdminDetails partnerAdminDetails, PartnerCompanyInfo partnerCompanyInfo, Long orderQty) {
        this.partnerAddress = partnerAddress;
        this.partnerAdmindetails = partnerAdminDetails;
        this.partnerCompanyinfo = partnerCompanyInfo;
        this.orderQty = orderQty;
    }
    
    /** full constructor */
    public PartnerCardOrder(PartnerCardOrderStatus partnerCardOrderStatus, PartnerAddress partnerAddress, PartnerAdminDetails partnerAdminDetails, PartnerCompanyInfo partnerCompanyInfo, Long orderQty, Date orderDate, String contactName, String notes, Long shipmentId) {
        this.partnerCardorderstatus = partnerCardOrderStatus;
        this.partnerAddress = partnerAddress;
        this.partnerAdmindetails = partnerAdminDetails;
        this.partnerCompanyinfo = partnerCompanyInfo;
        this.orderQty = orderQty;
        this.orderDate = orderDate;
        this.contactName = contactName;
        this.notes = notes;
        this.shipmentId = shipmentId;
    }

   
    // Property accessors

    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public PartnerCardOrderStatus getPartnerCardorderstatus() {
        return this.partnerCardorderstatus;
    }
    
    public void setPartnerCardorderstatus(PartnerCardOrderStatus partnerCardOrderStatus) {
        this.partnerCardorderstatus = partnerCardOrderStatus;
    }

    public PartnerAddress getPartnerAddress() {
        return this.partnerAddress;
    }
    
    public void setPartnerAddress(PartnerAddress partnerAddress) {
        this.partnerAddress = partnerAddress;
    }

    public PartnerAdminDetails getPartnerAdmindetails() {
        return this.partnerAdmindetails;
    }
    
    public void setPartnerAdmindetails(PartnerAdminDetails partnerAdminDetails) {
        this.partnerAdmindetails = partnerAdminDetails;
    }

    public PartnerCompanyInfo getPartnerCompanyinfo() {
        return this.partnerCompanyinfo;
    }
    
    public void setPartnerCompanyinfo(PartnerCompanyInfo partnerCompanyInfo) {
        this.partnerCompanyinfo = partnerCompanyInfo;
    }

    public Long getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(Long orderQty) {
        this.orderQty = orderQty;
    }

    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Long getShipmentId() {
        return this.shipmentId;
    }
    
    public void setShipmentId(Long shipmentId) {
        this.shipmentId = shipmentId;
    }
   








}