package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerCardorderstatus generated by MyEclipse - Hibernate Tools
 */

public class PartnerCardOrderStatus  implements java.io.Serializable {


    // Fields    

     private Long orderStatusid;
     private String orderStatus;
     private String displayInHistory;
     private Set partnerCardorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerCardOrderStatus() {
    }

	/** minimal constructor */
    public PartnerCardOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    
    /** full constructor */
    public PartnerCardOrderStatus(String orderStatus, Set partnerCardorders) {
        this.orderStatus = orderStatus;
        this.partnerCardorders = partnerCardorders;
    }

   
    // Property accessors

    public Long getOrderStatusid() {
        return this.orderStatusid;
    }
    
    public void setOrderStatusid(Long orderStatusid) {
        this.orderStatusid = orderStatusid;
    }

    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Set getPartnerCardorders() {
        return this.partnerCardorders;
    }
    
    public void setPartnerCardorders(Set partnerCardorders) {
        this.partnerCardorders = partnerCardorders;
    }

	/**
	 * @return the displayInHistory
	 */
	public String getDisplayInHistory() {
		return displayInHistory;
	}

	/**
	 * @param displayInHistory the displayInHistory to set
	 */
	public void setDisplayInHistory(String displayInHistory) {
		this.displayInHistory = displayInHistory;
	}
   








}