package com.marta.admin.hibernate;



/**
 * PartnerOrdershipment generated by MyEclipse - Hibernate Tools
 */

public class PartnerOrderShipment  implements java.io.Serializable {


    // Fields    

     private PartnerOrderShipmentId id;
     private String shippingCompany;
     private String shippingMode;
     private String trackingUrl;
     private String batchId;


    // Constructors

    /** default constructor */
    public PartnerOrderShipment() {
    }

    
    /** full constructor */
    public PartnerOrderShipment(String shippingCompany, String shippingMode, String trackingUrl, String batchId) {
        this.shippingCompany = shippingCompany;
        this.shippingMode = shippingMode;
        this.trackingUrl = trackingUrl;
        this.batchId = batchId;
    }

   
    // Property accessors

    public PartnerOrderShipmentId getId() {
        return this.id;
    }
    
    public void setId(PartnerOrderShipmentId id) {
        this.id = id;
    }

    public String getShippingCompany() {
        return this.shippingCompany;
    }
    
    public void setShippingCompany(String shippingCompany) {
        this.shippingCompany = shippingCompany;
    }

    public String getShippingMode() {
        return this.shippingMode;
    }
    
    public void setShippingMode(String shippingMode) {
        this.shippingMode = shippingMode;
    }

    public String getTrackingUrl() {
        return this.trackingUrl;
    }
    
    public void setTrackingUrl(String trackingUrl) {
        this.trackingUrl = trackingUrl;
    }

    public String getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }
   








}