package com.marta.admin.hibernate;

import java.util.Date;


/**
 * PartnerRegistration generated by MyEclipse - Hibernate Tools
 */

public class PartnerRegistration  implements java.io.Serializable {


    // Fields    

     private Long registrationRequestid;
     private Long companyId;
     private Date registrationRequestdate;
     private Date registrationApprovedate;
     private String registrationStatus;
     private Long primaryAdminid;
     private String comments;


    // Constructors

    /** default constructor */
    public PartnerRegistration() {
    }

	/** minimal constructor */
    public PartnerRegistration(Long companyId, String registrationStatus, Long primaryAdminid) {
        this.companyId = companyId;
        this.registrationStatus = registrationStatus;
        this.primaryAdminid = primaryAdminid;
    }
    
    /** full constructor */
    public PartnerRegistration(Long companyId, Date registrationRequestdate, Date registrationApprovedate, String registrationStatus, Long primaryAdminid, String comments) {
        this.companyId = companyId;
        this.registrationRequestdate = registrationRequestdate;
        this.registrationApprovedate = registrationApprovedate;
        this.registrationStatus = registrationStatus;
        this.primaryAdminid = primaryAdminid;
        this.comments = comments;
    }

   
    // Property accessors

    public Long getRegistrationRequestid() {
        return this.registrationRequestid;
    }
    
    public void setRegistrationRequestid(Long registrationRequestid) {
        this.registrationRequestid = registrationRequestid;
    }

    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Date getRegistrationRequestdate() {
        return this.registrationRequestdate;
    }
    
    public void setRegistrationRequestdate(Date registrationRequestdate) {
        this.registrationRequestdate = registrationRequestdate;
    }

    public Date getRegistrationApprovedate() {
        return this.registrationApprovedate;
    }
    
    public void setRegistrationApprovedate(Date registrationApprovedate) {
        this.registrationApprovedate = registrationApprovedate;
    }

    public String getRegistrationStatus() {
        return this.registrationStatus;
    }
    
    public void setRegistrationStatus(String registrationStatus) {
        this.registrationStatus = registrationStatus;
    }

    public Long getPrimaryAdminid() {
        return this.primaryAdminid;
    }
    
    public void setPrimaryAdminid(Long primaryAdminid) {
        this.primaryAdminid = primaryAdminid;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
   








}