package com.marta.admin.hibernate;



/**
 * PartnerAdmininfo generated by MyEclipse - Hibernate Tools
 */

public class PartnerAdminInfo  implements java.io.Serializable {


    // Fields    

     private String userName;
     private PartnerAdminDetails partnerAdminDetails;
     private String password;
     private String passwordStatus;
     private Long wrongAttempts;
     private String tempPassword;


    // Constructors

    /** default constructor */
    public PartnerAdminInfo() {
    }

	/** minimal constructor */
    public PartnerAdminInfo(PartnerAdminDetails partnerAdminDetails, String password, String passwordStatus) {
        this.partnerAdminDetails = partnerAdminDetails;
        this.password = password;
        this.passwordStatus = passwordStatus;
    }
    
    /** full constructor */
    public PartnerAdminInfo(PartnerAdminDetails partnerAdminDetails, String password, String passwordStatus, Long wrongAttempts, String tempPassword) {
        this.partnerAdminDetails = partnerAdminDetails;
        this.password = password;
        this.passwordStatus = passwordStatus;
        this.wrongAttempts = wrongAttempts;
        this.tempPassword = tempPassword;
    }

   
    // Property accessors

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public PartnerAdminDetails getPartnerAdminDetails() {
        return this.partnerAdminDetails;
    }
    
    public void setPartnerAdminDetails(PartnerAdminDetails partnerAdminDetails) {
        this.partnerAdminDetails = partnerAdminDetails;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getPasswordStatus() {
        return this.passwordStatus;
    }
    
    public void setPasswordStatus(String passwordStatus) {
        this.passwordStatus = passwordStatus;
    }

   
    

	/**
	 * @return the wrongAttempts
	 */
	public Long getWrongAttempts() {
		return wrongAttempts;
	}

	/**
	 * @param wrongAttempts the wrongAttempts to set
	 */
	public void setWrongAttempts(Long wrongAttempts) {
		this.wrongAttempts = wrongAttempts;
	}

	public String getTempPassword() {
        return this.tempPassword;
    }
    
    public void setTempPassword(String tempPassword) {
        this.tempPassword = tempPassword;
    }
   








}