package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerCompanyinfo generated by MyEclipse - Hibernate Tools
 */

public class PartnerCompanyInfo  implements java.io.Serializable {


    // Fields    

     private Long companyId;
     private PartnerCompanyStatus partnerCompanyStatus;
     private PartnerCompanyType partnerCompanyType;
     private String companyName;
     private String purchaseOrderno;
     private String nextfareCompanyId;
     private Set partnerCardorders = new HashSet(0);
     private Set partnerAdmindetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerCompanyInfo() {
    }

	/** minimal constructor */
    public PartnerCompanyInfo(PartnerCompanyStatus partnerCompanyStatus, PartnerCompanyType partnerCompanyType, String companyName, String purchaseOrderno) {
        this.partnerCompanyStatus = partnerCompanyStatus;
        this.partnerCompanyType = partnerCompanyType;
        this.companyName = companyName;
        this.purchaseOrderno = purchaseOrderno;
    }
    
    /** full constructor */
    public PartnerCompanyInfo(PartnerCompanyStatus partnerCompanyStatus, PartnerCompanyType partnerCompanyType, String companyName, String purchaseOrderno, String nextfareCompanyId, Set partnerCardorders, Set partnerAdmindetailses) {
        this.partnerCompanyStatus = partnerCompanyStatus;
        this.partnerCompanyType = partnerCompanyType;
        this.companyName = companyName;
        this.purchaseOrderno = purchaseOrderno;
        this.nextfareCompanyId = nextfareCompanyId;
        this.partnerCardorders = partnerCardorders;
        this.partnerAdmindetailses = partnerAdmindetailses;
    }

   
    // Property accessors

    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public PartnerCompanyStatus getPartnerCompanyStatus() {
        return this.partnerCompanyStatus;
    }
    
    public void setPartnerCompanyStatus(PartnerCompanyStatus partnerCompanyStatus) {
        this.partnerCompanyStatus = partnerCompanyStatus;
    }

    public PartnerCompanyType getPartnerCompanyType() {
        return this.partnerCompanyType;
    }
    
    public void setPartnerCompanyType(PartnerCompanyType partnerCompanyType) {
        this.partnerCompanyType = partnerCompanyType;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getPurchaseOrderno() {
        return this.purchaseOrderno;
    }
    
    public void setPurchaseOrderno(String purchaseOrderno) {
        this.purchaseOrderno = purchaseOrderno;
    }

    public String getNextfareCompanyId() {
        return this.nextfareCompanyId;
    }
    
    public void setNextfareCompanyId(String nextfareCompanyId) {
        this.nextfareCompanyId = nextfareCompanyId;
    }

    public Set getPartnerCardorders() {
        return this.partnerCardorders;
    }
    
    public void setPartnerCardorders(Set partnerCardorders) {
        this.partnerCardorders = partnerCardorders;
    }

    public Set getPartnerAdmindetailses() {
        return this.partnerAdmindetailses;
    }
    
    public void setPartnerAdmindetailses(Set partnerAdmindetailses) {
        this.partnerAdmindetailses = partnerAdmindetailses;
    }
   








}