package com.marta.admin.hibernate;

import java.util.Date;


/**
 * PartnerNotes generated by MyEclipse - Hibernate Tools
 */

public class PartnerNotes  implements java.io.Serializable {


    // Fields    

     private Long custid;
     private Long reasonCodeId;
     private String notes;
     private Date insertedDtm;
     private Long noteId;


    // Constructors

    /** default constructor */
    public PartnerNotes() {
    }

	/** minimal constructor */
    public PartnerNotes(Date insertedDtm, Long noteId) {
        this.insertedDtm = insertedDtm;
        this.noteId = noteId;
    }
    
    /** full constructor */
    public PartnerNotes(Long reasonCodeId, String notes, Date insertedDtm, Long noteId) {
        this.reasonCodeId = reasonCodeId;
        this.notes = notes;
        this.insertedDtm = insertedDtm;
        this.noteId = noteId;
    }

   
    // Property accessors

    public Long getCustid() {
        return this.custid;
    }
    
    public void setCustid(Long custid) {
        this.custid = custid;
    }

    public Long getReasonCodeId() {
        return this.reasonCodeId;
    }
    
    public void setReasonCodeId(Long reasonCodeId) {
        this.reasonCodeId = reasonCodeId;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Date getInsertedDtm() {
        return this.insertedDtm;
    }
    
    public void setInsertedDtm(Date insertedDtm) {
        this.insertedDtm = insertedDtm;
    }

    public Long getNoteId() {
        return this.noteId;
    }
    
    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }
   








}