package com.marta.admin.hibernate;

import java.util.Date;

import com.marta.admin.hibernate.PartnerBatchDetailsId;



/**
 * PartnerBatchdetails generated by MyEclipse - Hibernate Tools
 */

public class PartnerBatchDetails  implements java.io.Serializable {


    // Fields    

     private PartnerBatchDetailsId id;
     private String cardSerialNo;
     private String action;
     private String customerMemberId;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private String phoneType;
     private String benefitsId;
     private String benefitsId2;
     private String benefitsId3;
     private String benefitsId4;
     private String benefitactionid;
     private String benefitactionid2;
     private String benefitactionid3;
     private String benefitactionid4;
     private String processed;
     private String success;
     private String errorMessage;
     private String test;
     private String partnerId;
     private String notes;
     private String replaceCardSerialId;
     private String message;
     private Date date_added;


    // Constructors

    /** default constructor */
    public PartnerBatchDetails() {
    }

	/** minimal constructor */
    public PartnerBatchDetails(String cardSerialNo) {
        this.cardSerialNo = cardSerialNo;
    }
    
    /** full constructor */
    public PartnerBatchDetails(String cardSerialNo, String action, String customerMemberId, String firstName, String lastName, String email, String phone, String phoneType, String benefitsId,String benefitsId2,String benefitsId3,String benefitsId4,String benefitactionid,String benefitactionid2,String benefitactionid3,String benefitactionid4, String processed, String success, String errorMessage, String test, String partnerId, String notes, String replaceCardSerialId, String message, Date date_added) {
        this.cardSerialNo = cardSerialNo;
        this.action = action;
        this.customerMemberId = customerMemberId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.phoneType = phoneType;
        this.benefitsId = benefitsId;
        this.benefitsId2 = benefitsId2;
        this.benefitsId3 = benefitsId3;
        this.benefitsId4 = benefitsId4;
        this.benefitactionid = benefitactionid;
        this.benefitactionid2 = benefitactionid2;
        this.benefitactionid3 = benefitactionid3;
        this.benefitactionid4 = benefitactionid4;
        this.processed = processed;
        this.success = success;
        this.errorMessage = errorMessage;
        this.test = test;
        this.partnerId = partnerId;
        this.notes = notes;
        this.replaceCardSerialId = replaceCardSerialId;
        this.message = message;
        this.date_added = date_added;
    }

   
    // Property accessors

    
    
    public PartnerBatchDetailsId getId() {
        return this.id;
    }
    
    public Date getDate_added() {
		return date_added;
	}

	public void setDate_added(Date date_added) {
		this.date_added = date_added;
	}

	public String getBenefitactionid2() {
		return benefitactionid2;
	}

	public void setBenefitactionid2(String benefitactionid2) {
		this.benefitactionid2 = benefitactionid2;
	}

	public String getBenefitactionid3() {
		return benefitactionid3;
	}

	public void setBenefitactionid3(String benefitactionid3) {
		this.benefitactionid3 = benefitactionid3;
	}

	public String getBenefitactionid4() {
		return benefitactionid4;
	}

	public void setBenefitactionid4(String benefitactionid4) {
		this.benefitactionid4 = benefitactionid4;
	}

	public String getBenefitsId2() {
		return benefitsId2;
	}

	public void setBenefitsId2(String benefitsId2) {
		this.benefitsId2 = benefitsId2;
	}

	public String getBenefitsId3() {
		return benefitsId3;
	}

	public void setBenefitsId3(String benefitsId3) {
		this.benefitsId3 = benefitsId3;
	}

	public String getBenefitsId4() {
		return benefitsId4;
	}

	public void setBenefitsId4(String benefitsId4) {
		this.benefitsId4 = benefitsId4;
	}

	public String getBenefitactionid() {
		return benefitactionid;
	}

	public void setBenefitactionid(String benefitactionid) {
		this.benefitactionid = benefitactionid;
	}

	public void setId(PartnerBatchDetailsId id) {
        this.id = id;
    }

    public String getCardSerialNo() {
        return this.cardSerialNo;
    }
    
    public void setCardSerialNo(String cardSerialNo) {
        this.cardSerialNo = cardSerialNo;
    }

    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    public String getCustomerMemberId() {
        return this.customerMemberId;
    }
    
    public void setCustomerMemberId(String customerMemberId) {
        this.customerMemberId = customerMemberId;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    public String getBenefitsId() {
        return this.benefitsId;
    }
    
    public void setBenefitsId(String benefitsId) {
        this.benefitsId = benefitsId;
    }

    public String getProcessed() {
        return this.processed;
    }
    
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    public String getSuccess() {
        return this.success;
    }
    
    public void setSuccess(String success) {
        this.success = success;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getTest() {
        return this.test;
    }
    
    public void setTest(String test) {
        this.test = test;
    }

    public String getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getReplaceCardSerialId() {
        return this.replaceCardSerialId;
    }
    
    public void setReplaceCardSerialId(String replaceCardSerialId) {
        this.replaceCardSerialId = replaceCardSerialId;
    }

    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
   








}