package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerAdmindetails generated by MyEclipse - Hibernate Tools
 */

public class PartnerAdminDetails  implements java.io.Serializable {


    // Fields    

     private Long partnerId;
     private PartnerAdminRole partnerAdminRole;
     private PartnerSecurityQuestion partnerSecurityquestion;
     private PartnerCompanyInfo partnerCompanyInfo;
     private String lastName;
     private String firstName;
     private String phone1;
     private String phone2;
     private String fax;
     private String securityAnswer;
     private String notes;
     private String statusFlag;
     private String email;
     private Set partnerAddresses = new HashSet(0);
     private Set partnerCardorders = new HashSet(0);
     private Set partnerAdmininfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerAdminDetails() {
    }

	/** minimal constructor */
    public PartnerAdminDetails(PartnerAdminRole partnerAdminRole, PartnerSecurityQuestion partnerSecurityQuestion, PartnerCompanyInfo partnerCompanyInfo, String lastName, String firstName, String phone1, String securityAnswer) {
        this.partnerAdminRole = partnerAdminRole;
        this.partnerSecurityquestion = partnerSecurityQuestion;
        this.partnerCompanyInfo = partnerCompanyInfo;
        this.lastName = lastName;
        this.firstName = firstName;
        this.phone1 = phone1;
        this.securityAnswer = securityAnswer;
    }
    
    /** full constructor */
    public PartnerAdminDetails(PartnerAdminRole partnerAdminRole, PartnerSecurityQuestion partnerSecurityQuestion, PartnerCompanyInfo partnerCompanyInfo, String lastName, String firstName, String phone1, String phone2, String fax, String securityAnswer, String notes, String statusFlag, String email, Set partnerAddresses, Set partnerCardorders, Set partnerAdmininfos) {
        this.partnerAdminRole = partnerAdminRole;
        this.partnerSecurityquestion = partnerSecurityQuestion;
        this.partnerCompanyInfo = partnerCompanyInfo;
        this.lastName = lastName;
        this.firstName = firstName;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.fax = fax;
        this.securityAnswer = securityAnswer;
        this.notes = notes;
        this.statusFlag = statusFlag;
        this.email = email;
        this.partnerAddresses = partnerAddresses;
        this.partnerCardorders = partnerCardorders;
        this.partnerAdmininfos = partnerAdmininfos;
    }

   
    // Property accessors

    public Long getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    public PartnerAdminRole getPartnerAdminRole() {
        return this.partnerAdminRole;
    }
    
    public void setPartnerAdminRole(PartnerAdminRole partnerAdminRole) {
        this.partnerAdminRole = partnerAdminRole;
    }

    public PartnerSecurityQuestion getPartnerSecurityquestion() {
        return this.partnerSecurityquestion;
    }
    
    public void setPartnerSecurityquestion(PartnerSecurityQuestion partnerSecurityQuestion) {
        this.partnerSecurityquestion = partnerSecurityQuestion;
    }

    public PartnerCompanyInfo getPartnerCompanyInfo() {
        return this.partnerCompanyInfo;
    }
    
    public void setPartnerCompanyInfo(PartnerCompanyInfo partnerCompanyInfo) {
        this.partnerCompanyInfo = partnerCompanyInfo;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getSecurityAnswer() {
        return this.securityAnswer;
    }
    
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getStatusFlag() {
        return this.statusFlag;
    }
    
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set getPartnerAddresses() {
        return this.partnerAddresses;
    }
    
    public void setPartnerAddresses(Set partnerAddresses) {
        this.partnerAddresses = partnerAddresses;
    }

    public Set getPartnerCardorders() {
        return this.partnerCardorders;
    }
    
    public void setPartnerCardorders(Set partnerCardorders) {
        this.partnerCardorders = partnerCardorders;
    }

    public Set getPartnerAdmininfos() {
        return this.partnerAdmininfos;
    }
    
    public void setPartnerAdmininfos(Set partnerAdmininfos) {
        this.partnerAdmininfos = partnerAdmininfos;
    }

}