package com.marta.admin.hibernate;

import java.util.Date;


/**
 * PartnerNewregistration generated by MyEclipse - Hibernate Tools
 */

public class PartnerNewRegistration  implements java.io.Serializable {


    // Fields    

     private Long registrationRequestid;
     private PartnerRegistrationStatus partnerRegistrationstatus;
     private String companyName;
     private Long  companyTypeid;
     private String lastName;
     private String firstName;
     private String phone1;
     private String phone2;
     private String fax;
     private String email;
     private String userName;
     private String password;
     private Long securityQuestionid;
     private String securityAnswer;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String zip;
     private String country;
     private String senderNotes;
     private Date registrationRequestdate;
     private Date registrationApprovedate;


    // Constructors

    /** default constructor */
    public PartnerNewRegistration() {
    }

	/** minimal constructor */
    public PartnerNewRegistration(Long registrationRequestid, String companyName, Long companyTypeid) {
        this.registrationRequestid = registrationRequestid;
        this.companyName = companyName;
        this.companyTypeid = companyTypeid;
    }
    
    /** full constructor */
    public PartnerNewRegistration(Long registrationRequestid, PartnerRegistrationStatus partnerRegistrationstatus, String companyName, Long companyTypeid, String lastName, String firstName, String phone1, String phone2, String fax, String email, String userName, String password, Long securityQuestionid, String securityAnswer, String address1, String address2, String city, String state, String zip, String country, String senderNotes, Date registrationRequestdate, Date registrationApprovedate) {
        this.registrationRequestid = registrationRequestid;
        this.partnerRegistrationstatus = partnerRegistrationstatus;
        this.companyName = companyName;
        this.companyTypeid = companyTypeid;
        this.lastName = lastName;
        this.firstName = firstName;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.fax = fax;
        this.email = email;
        this.userName = userName;
        this.password = password;
        this.securityQuestionid = securityQuestionid;
        this.securityAnswer = securityAnswer;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.country = country;
        this.senderNotes = senderNotes;
        this.registrationRequestdate = registrationRequestdate;
        this.registrationApprovedate = registrationApprovedate;
    }

   
    // Property accessors

    public Long getRegistrationRequestid() {
        return this.registrationRequestid;
    }
    
    public void setRegistrationRequestid(Long registrationRequestid) {
        this.registrationRequestid = registrationRequestid;
    }

    public PartnerRegistrationStatus getPartnerRegistrationstatus() {
        return this.partnerRegistrationstatus;
    }
    
    public void setPartnerRegistrationstatus(PartnerRegistrationStatus partnerRegistrationstatus) {
        this.partnerRegistrationstatus = partnerRegistrationstatus;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public Long getCompanyTypeid() {
        return this.companyTypeid;
    }
    
    public void setCompanyTypeid(Long companyTypeid) {
        this.companyTypeid = companyTypeid;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Long getSecurityQuestionid() {
        return this.securityQuestionid;
    }
    
    public void setSecurityQuestionid(Long securityQuestionid) {
        this.securityQuestionid = securityQuestionid;
    }

    public String getSecurityAnswer() {
        return this.securityAnswer;
    }
    
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public String getSenderNotes() {
        return this.senderNotes;
    }
    
    public void setSenderNotes(String senderNotes) {
        this.senderNotes = senderNotes;
    }

    public Date getRegistrationRequestdate() {
        return this.registrationRequestdate;
    }
    
    public void setRegistrationRequestdate(Date registrationRequestdate) {
        this.registrationRequestdate = registrationRequestdate;
    }

    public Date getRegistrationApprovedate() {
        return this.registrationApprovedate;
    }
    
    public void setRegistrationApprovedate(Date registrationApprovedate) {
        this.registrationApprovedate = registrationApprovedate;
    }
   








}