package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerBatchstatuses generated by MyEclipse - Hibernate Tools
 */

public class PartnerBatchStatuses  implements java.io.Serializable {


    // Fields    

     private Long statusId;
     private String statusDesc;
     private Set partnerBatchjobs = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerBatchStatuses() {
    }

	/** minimal constructor */
    public PartnerBatchStatuses(Long statusId, String statusDesc) {
        this.statusId = statusId;
        this.statusDesc = statusDesc;
    }
    
    /** full constructor */
    public PartnerBatchStatuses(Long statusId, String statusDesc, Set partnerBatchjobs) {
        this.statusId = statusId;
        this.statusDesc = statusDesc;
        this.partnerBatchjobs = partnerBatchjobs;
    }

   
    // Property accessors

    public Long getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Long statusId) {
        this.statusId = statusId;
    }

    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    public Set getPartnerBatchjobs() {
        return this.partnerBatchjobs;
    }
    
    public void setPartnerBatchjobs(Set partnerBatchjobs) {
        this.partnerBatchjobs = partnerBatchjobs;
    }
   








}