package com.marta.admin.hibernate;



/**
 * PartnerTransactiondetails generated by MyEclipse - Hibernate Tools
 */

public class PartnerTransactionDetails  implements java.io.Serializable {


    // Fields    

     private Long seqId;
     private String cardSerialNo;
     private String action;
     private String customerMemberId;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private String phoneType;
     private String benefitsId;
     private String success;
     private String errorMessage;
     private String partnerId;
     private String adminId;
     private String notes;
     private String replaceCardSerialId;


    // Constructors

    /** default constructor */
    public PartnerTransactionDetails() {
    }

    
    /** full constructor */
    public PartnerTransactionDetails(String cardSerialNo, String action, String customerMemberId, String firstName, String lastName, String email, String phone, String phoneType, String benefitsId, String success, String errorMessage, String partnerId, String adminId, String notes, String replaceCardSerialId) {
        this.cardSerialNo = cardSerialNo;
        this.action = action;
        this.customerMemberId = customerMemberId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.phoneType = phoneType;
        this.benefitsId = benefitsId;
        this.success = success;
        this.errorMessage = errorMessage;
        this.partnerId = partnerId;
        this.adminId = adminId;
        this.notes = notes;
        this.replaceCardSerialId = replaceCardSerialId;
    }

   
    // Property accessors

    public Long getSeqId() {
        return this.seqId;
    }
    
    public void setSeqId(Long seqId) {
        this.seqId = seqId;
    }

    public String getCardSerialNo() {
        return this.cardSerialNo;
    }
    
    public void setCardSerialNo(String cardSerialNo) {
        this.cardSerialNo = cardSerialNo;
    }

    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    public String getCustomerMemberId() {
        return this.customerMemberId;
    }
    
    public void setCustomerMemberId(String customerMemberId) {
        this.customerMemberId = customerMemberId;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    public String getBenefitsId() {
        return this.benefitsId;
    }
    
    public void setBenefitsId(String benefitsId) {
        this.benefitsId = benefitsId;
    }

    public String getSuccess() {
        return this.success;
    }
    
    public void setSuccess(String success) {
        this.success = success;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getReplaceCardSerialId() {
        return this.replaceCardSerialId;
    }
    
    public void setReplaceCardSerialId(String replaceCardSerialId) {
        this.replaceCardSerialId = replaceCardSerialId;
    }
   








}