package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerAdminrole generated by MyEclipse - Hibernate Tools
 */

public class PartnerAdminRole  implements java.io.Serializable {


    // Fields    

     private Long roleid;
     private String roleName;
     private String description;
     private Set partnerAdmindetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerAdminRole() {
    }

	/** minimal constructor */
    public PartnerAdminRole(String roleName) {
        this.roleName = roleName;
    }
    
    /** full constructor */
    public PartnerAdminRole(String roleName, String description, Set partnerAdmindetailses) {
        this.roleName = roleName;
        this.description = description;
        this.partnerAdmindetailses = partnerAdmindetailses;
    }

   
    // Property accessors

    public Long getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPartnerAdmindetailses() {
        return this.partnerAdmindetailses;
    }
    
    public void setPartnerAdmindetailses(Set partnerAdmindetailses) {
        this.partnerAdmindetailses = partnerAdmindetailses;
    }
   








}