package com.marta.admin.hibernate;



/**
 * PartnerAdmin generated by MyEclipse - Hibernate Tools
 */

public class PartnerAdmin  implements java.io.Serializable {


    // Fields    

     private Long adminId;
     private String password;
     private String firstName;
     private String lastName;
     private String adminRole;
     private String companyName;
     private String userName;
     private String street1;
     private String street2;
     private String city;
     private String state;
     private String zipcode;
     private String phone1;
     private String phone2;
     private String fax;
     private String securityAnswer;
     private String tempPassword;
     private String passwordIndicator;
     private Long securityAnswerId;
     private String email;
     private String status;
     private String passwordStatus;


    // Constructors

    /** default constructor */
    public PartnerAdmin() {
    }

    
    /** full constructor */
    public PartnerAdmin(String password, String firstName, String lastName, String adminRole, String companyName, String userName, String street1, String street2, String city, String state, String zipcode, String phone1, String phone2, String fax, String securityAnswer, String tempPassword, String passwordIndicator, Long securityAnswerId, String email, String status, String passwordStatus) {
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.adminRole = adminRole;
        this.companyName = companyName;
        this.userName = userName;
        this.street1 = street1;
        this.street2 = street2;
        this.city = city;
        this.state = state;
        this.zipcode = zipcode;
        this.phone1 = phone1;
        this.phone2 = phone2;
        this.fax = fax;
        this.securityAnswer = securityAnswer;
        this.tempPassword = tempPassword;
        this.passwordIndicator = passwordIndicator;
        this.securityAnswerId = securityAnswerId;
        this.email = email;
        this.status = status;
        this.passwordStatus = passwordStatus;
    }

   
    // Property accessors

    public Long getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAdminRole() {
        return this.adminRole;
    }
    
    public void setAdminRole(String adminRole) {
        this.adminRole = adminRole;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }

    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getSecurityAnswer() {
        return this.securityAnswer;
    }
    
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    public String getTempPassword() {
        return this.tempPassword;
    }
    
    public void setTempPassword(String tempPassword) {
        this.tempPassword = tempPassword;
    }

    public String getPasswordIndicator() {
        return this.passwordIndicator;
    }
    
    public void setPasswordIndicator(String passwordIndicator) {
        this.passwordIndicator = passwordIndicator;
    }

    public Long getSecurityAnswerId() {
        return this.securityAnswerId;
    }
    
    public void setSecurityAnswerId(Long securityAnswerId) {
        this.securityAnswerId = securityAnswerId;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getPasswordStatus() {
        return this.passwordStatus;
    }
    
    public void setPasswordStatus(String passwordStatus) {
        this.passwordStatus = passwordStatus;
    }
   








}