package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerAddress generated by MyEclipse - Hibernate Tools
 */

public class PartnerAddress  implements java.io.Serializable {


    // Fields    

     private Long addressId;
     private PartnerAdminDetails partnerAdminDetails;
     private PartnerAddressType partnerAddresstype;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String zip;
     //added to save nickname
     private String fullname;
     private String nickname;
     private Set partnerCardorders = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerAddress() {
    }

	/** minimal constructor */
    public PartnerAddress(PartnerAdminDetails partnerAdminDetails, PartnerAddressType partnerAddressType, String address1, String state, String zip) {
        this.partnerAdminDetails = partnerAdminDetails;
        this.partnerAddresstype = partnerAddressType;
        this.address1 = address1;
        this.state = state;
        this.zip = zip;
    }
    
    /** full constructor */
    public PartnerAddress(PartnerAdminDetails partnerAdminDetails, PartnerAddressType partnerAddressType, String address1, String address2, String city, String state, String zip, Set partnerCardorders) {
        this.partnerAdminDetails = partnerAdminDetails;
        this.partnerAddresstype = partnerAddressType;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.partnerCardorders = partnerCardorders;
    }

   
    // Property accessors

    public Long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    public PartnerAdminDetails getPartnerAdminDetails() {
        return this.partnerAdminDetails;
    }
    
    public void setPartnerAdminDetails(PartnerAdminDetails partnerAdminDetails) {
        this.partnerAdminDetails = partnerAdminDetails;
    }

    public PartnerAddressType getPartnerAddresstype() {
        return this.partnerAddresstype;
    }
    
    public void setPartnerAddresstype(PartnerAddressType partnerAddressType) {
        this.partnerAddresstype = partnerAddressType;
    }

    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public Set getPartnerCardorders() {
        return this.partnerCardorders;
    }
    
    public void setPartnerCardorders(Set partnerCardorders) {
        this.partnerCardorders = partnerCardorders;
    }

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
   








}