package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerCompanytype generated by MyEclipse - Hibernate Tools
 */

public class PartnerCompanyType  implements java.io.Serializable {


    // Fields    

     private Long companyTypeId;
     private String companyType;
     private Set partnerCompanyinfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerCompanyType() {
    }

    
    /** full constructor */
    public PartnerCompanyType(String companyType, Set partnerCompanyinfos) {
        this.companyType = companyType;
        this.partnerCompanyinfos = partnerCompanyinfos;
    }

   
    // Property accessors

    public Long getCompanyTypeId() {
        return this.companyTypeId;
    }
    
    public void setCompanyTypeId(Long companyTypeId) {
        this.companyTypeId = companyTypeId;
    }

    public String getCompanyType() {
        return this.companyType;
    }
    
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    public Set getPartnerCompanyinfos() {
        return this.partnerCompanyinfos;
    }
    
    public void setPartnerCompanyinfos(Set partnerCompanyinfos) {
        this.partnerCompanyinfos = partnerCompanyinfos;
    }
   








}