package com.marta.admin.hibernate;

import com.marta.admin.hibernate.PartnerBatchDetailsHistoryId;



/**
 * PartnerBatchdetailsHistory generated by MyEclipse - Hibernate Tools
 */

public class PartnerBatchDetailsHistory  implements java.io.Serializable {


    // Fields    

     private PartnerBatchDetailsHistoryId id;
     private String cardSerialNo;
     private String action;
     private String customerMemberId;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private String phoneType;
     private String benefitsId;
     private String benefitsId2;
     private String benefitsId3;
     private String benefitsId4;
     private String processed;
     private String success;
     private String errorMessage;
     private String test;
     private String partnerId;
     private String notes;
     private String replaceCardSerialId;
     private String benefitActionId;
     private String benefitActionId2;
     private String benefitActionId3;
     private String benefitActionId4;
     private String nfsBenefitId;
     private String benefitType;
     private String benefitType2;
     private String benefitType3;
     private String benefitType4;


    // Constructors

    /** default constructor */
    public PartnerBatchDetailsHistory() {
    }

	/** minimal constructor */
    public PartnerBatchDetailsHistory(PartnerBatchDetailsHistoryId id) {
        this.id = id;
    }
    
    /** full constructor */
    public PartnerBatchDetailsHistory(PartnerBatchDetailsHistoryId id, String cardSerialNo, String action, String customerMemberId, String firstName, String lastName, String email, String phone, String phoneType, String benefitsId,String benefitsId2,String benefitsId3,String benefitsId4, String processed, String success, String errorMessage, String test, String partnerId, String notes, String replaceCardSerialId, String benefitActionId,String benefitActionId2,String benefitActionId3,String benefitActionId4, String nfsBenefitId, String benefitType,String benefitType2,String benefitType3,String benefitType4) {
        this.id = id;
        this.cardSerialNo = cardSerialNo;
        this.action = action;
        this.customerMemberId = customerMemberId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.phoneType = phoneType;
        this.benefitsId = benefitsId;
        this.benefitsId2 = benefitsId2;
        this.benefitsId3 = benefitsId3;
        this.benefitsId4 = benefitsId4;
        this.processed = processed;
        this.success = success;
        this.errorMessage = errorMessage;
        this.test = test;
        this.partnerId = partnerId;
        this.notes = notes;
        this.replaceCardSerialId = replaceCardSerialId;
        this.benefitActionId = benefitActionId;
        this.benefitActionId2 = benefitActionId2;
        this.benefitActionId3 = benefitActionId3;
        this.benefitActionId4 = benefitActionId4;
        this.nfsBenefitId = nfsBenefitId;
        this.benefitType = benefitType;
        this.benefitType2 = benefitType2;
        this.benefitType3 = benefitType3;
        this.benefitType4 = benefitType4;
    }

   
    // Property accessors

    
    
    public PartnerBatchDetailsHistoryId getId() {
        return this.id;
    }
    
    public String getBenefitType2() {
		return benefitType2;
	}

	public void setBenefitType2(String benefitType2) {
		this.benefitType2 = benefitType2;
	}

	public String getBenefitType3() {
		return benefitType3;
	}

	public void setBenefitType3(String benefitType3) {
		this.benefitType3 = benefitType3;
	}

	public String getBenefitType4() {
		return benefitType4;
	}

	public void setBenefitType4(String benefitType4) {
		this.benefitType4 = benefitType4;
	}

	public String getBenefitsId2() {
		return benefitsId2;
	}

	public void setBenefitsId2(String benefitsId2) {
		this.benefitsId2 = benefitsId2;
	}

	public String getBenefitsId3() {
		return benefitsId3;
	}

	public void setBenefitsId3(String benefitsId3) {
		this.benefitsId3 = benefitsId3;
	}

	public String getBenefitsId4() {
		return benefitsId4;
	}

	public void setBenefitsId4(String benefitsId4) {
		this.benefitsId4 = benefitsId4;
	}

	public String getBenefitActionId2() {
		return benefitActionId2;
	}

	public void setBenefitActionId2(String benefitActionId2) {
		this.benefitActionId2 = benefitActionId2;
	}

	public String getBenefitActionId3() {
		return benefitActionId3;
	}

	public void setBenefitActionId3(String benefitActionId3) {
		this.benefitActionId3 = benefitActionId3;
	}

	public String getBenefitActionId4() {
		return benefitActionId4;
	}

	public void setBenefitActionId4(String benefitActionId4) {
		this.benefitActionId4 = benefitActionId4;
	}

	public void setId(PartnerBatchDetailsHistoryId id) {
        this.id = id;
    }

    public String getCardSerialNo() {
        return this.cardSerialNo;
    }
    
    public void setCardSerialNo(String cardSerialNo) {
        this.cardSerialNo = cardSerialNo;
    }

    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    public String getCustomerMemberId() {
        return this.customerMemberId;
    }
    
    public void setCustomerMemberId(String customerMemberId) {
        this.customerMemberId = customerMemberId;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }

    public String getBenefitsId() {
        return this.benefitsId;
    }
    
    public void setBenefitsId(String benefitsId) {
        this.benefitsId = benefitsId;
    }

    public String getProcessed() {
        return this.processed;
    }
    
    public void setProcessed(String processed) {
        this.processed = processed;
    }

    public String getSuccess() {
        return this.success;
    }
    
    public void setSuccess(String success) {
        this.success = success;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getTest() {
        return this.test;
    }
    
    public void setTest(String test) {
        this.test = test;
    }

    public String getPartnerId() {
        return this.partnerId;
    }
    
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getReplaceCardSerialId() {
        return this.replaceCardSerialId;
    }
    
    public void setReplaceCardSerialId(String replaceCardSerialId) {
        this.replaceCardSerialId = replaceCardSerialId;
    }

    public String getBenefitActionId() {
        return this.benefitActionId;
    }
    
    public void setBenefitActionId(String benefitActionId) {
        this.benefitActionId = benefitActionId;
    }

    public String getNfsBenefitId() {
        return this.nfsBenefitId;
    }
    
    public void setNfsBenefitId(String nfsBenefitId) {
        this.nfsBenefitId = nfsBenefitId;
    }

    public String getBenefitType() {
        return this.benefitType;
    }
    
    public void setBenefitType(String benefitType) {
        this.benefitType = benefitType;
    }
   








}