package com.marta.admin.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * PartnerSecurityquestion generated by MyEclipse - Hibernate Tools
 */

public class PartnerSecurityQuestion  implements java.io.Serializable {


    // Fields    

     private Long securityQuestionid;
     private String securityQuestion;
     private Set partnerAdmindetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public PartnerSecurityQuestion() {
    }

	/** minimal constructor */
    public PartnerSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }
    
    /** full constructor */
    public PartnerSecurityQuestion(String securityQuestion, Set partnerAdmindetailses) {
        this.securityQuestion = securityQuestion;
        this.partnerAdmindetailses = partnerAdmindetailses;
    }

   
    // Property accessors

    public Long getSecurityQuestionid() {
        return this.securityQuestionid;
    }
    
    public void setSecurityQuestionid(Long securityQuestionid) {
        this.securityQuestionid = securityQuestionid;
    }

    public String getSecurityQuestion() {
        return this.securityQuestion;
    }
    
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }

    public Set getPartnerAdmindetailses() {
        return this.partnerAdmindetailses;
    }
    
    public void setPartnerAdmindetailses(Set partnerAdmindetailses) {
        this.partnerAdmindetailses = partnerAdmindetailses;
    }
   








}