package com.marta.admin.hibernate;



/**
 * TmaCompanyLink generated by MyEclipse - Hibernate Tools
 */

public class TmaCompanyLink  implements java.io.Serializable {


    // Fields    

     private TmaCompanyLinkId id;


    // Constructors

    /** default constructor */
    public TmaCompanyLink() {
    }

    
    /** full constructor */
    public TmaCompanyLink(TmaCompanyLinkId id) {
        this.id = id;
    }

   
    // Property accessors

    public TmaCompanyLinkId getId() {
        return this.id;
    }
    
    public void setId(TmaCompanyLinkId id) {
        this.id = id;
    }
   








}