package com.marta.admin.hibernate;



/**
 * TmaCompanyLinkId generated by MyEclipse - Hibernate Tools
 */

public class TmaCompanyLinkId  implements java.io.Serializable {


    // Fields    

     private Long tmaId;
     private Long companyId;
     private String companyUsername;
     private String companyName;


    // Constructors

    /** default constructor */
    public TmaCompanyLinkId() {
    }

    
    /** full constructor */
    public TmaCompanyLinkId(Long tmaId, Long companyId, String companyUsername, String companyName) {
        this.tmaId = tmaId;
        this.companyId = companyId;
        this.companyUsername = companyUsername;
        this.companyName = companyName;
    }

   
    // Property accessors

    public Long getTmaId() {
        return this.tmaId;
    }
    
    public void setTmaId(Long tmaId) {
        this.tmaId = tmaId;
    }

    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public String getCompanyUsername() {
        return this.companyUsername;
    }
    
    public void setCompanyUsername(String companyUsername) {
        this.companyUsername = companyUsername;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmaCompanyLinkId) ) return false;
		 TmaCompanyLinkId castOther = ( TmaCompanyLinkId ) other; 
         
		 return ( (this.getTmaId()==castOther.getTmaId()) || ( this.getTmaId()!=null && castOther.getTmaId()!=null && this.getTmaId().equals(castOther.getTmaId()) ) )
 && ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) )
 && ( (this.getCompanyUsername()==castOther.getCompanyUsername()) || ( this.getCompanyUsername()!=null && castOther.getCompanyUsername()!=null && this.getCompanyUsername().equals(castOther.getCompanyUsername()) ) )
 && ( (this.getCompanyName()==castOther.getCompanyName()) || ( this.getCompanyName()!=null && castOther.getCompanyName()!=null && this.getCompanyName().equals(castOther.getCompanyName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTmaId() == null ? 0 : this.getTmaId().hashCode() );
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         result = 37 * result + ( getCompanyUsername() == null ? 0 : this.getCompanyUsername().hashCode() );
         result = 37 * result + ( getCompanyName() == null ? 0 : this.getCompanyName().hashCode() );
         return result;
   }   





}