package com.marta.admin.hibernate;



/**
 * TmaInformation generated by MyEclipse - Hibernate Tools
 */

public class TmaInformation  implements java.io.Serializable {


    // Fields    

     private Long tmaId;
     private String tmaName;
     private String tmaUsername;
     private String tmaPassword;
     private String tmaEmail;
     private Long tmaPhone;
     private String tmaAddress;
     private String tmaPasswordStatus;
     private Long tmaWrongAttempts;
     private String tmaTmpPassword;
     private String tmaFax;
     private String tmaCity;
     private String tmaZip;
     private String tmaFirstname;
     private String tmaLastname;
     private String tmaState;


    // Constructors

    /** default constructor */
    public TmaInformation() {
    }

    
    /** full constructor */
    public TmaInformation(String tmaName, String tmaUsername, String tmaPassword, String tmaEmail, Long tmaPhone, String tmaAddress, String tmaPasswordStatus, Long tmaWrongAttempts, String tmaTmpPassword, String tmaFax, String tmaCity, String tmaZip, String tmaFirstname, String tmaLastname, String tmaState) {
        this.tmaName = tmaName;
        this.tmaUsername = tmaUsername;
        this.tmaPassword = tmaPassword;
        this.tmaEmail = tmaEmail;
        this.tmaPhone = tmaPhone;
        this.tmaAddress = tmaAddress;
        this.tmaPasswordStatus = tmaPasswordStatus;
        this.tmaWrongAttempts = tmaWrongAttempts;
        this.tmaTmpPassword = tmaTmpPassword;
        this.tmaFax = tmaFax;
        this.tmaCity = tmaCity;
        this.tmaZip = tmaZip;
        this.tmaFirstname = tmaFirstname;
        this.tmaLastname = tmaLastname;
        this.tmaState = tmaState;
    }

   
    // Property accessors

    public Long getTmaId() {
        return this.tmaId;
    }
    
    public void setTmaId(Long tmaId) {
        this.tmaId = tmaId;
    }

    public String getTmaName() {
        return this.tmaName;
    }
    
    public void setTmaName(String tmaName) {
        this.tmaName = tmaName;
    }

    public String getTmaUsername() {
        return this.tmaUsername;
    }
    
    public void setTmaUsername(String tmaUsername) {
        this.tmaUsername = tmaUsername;
    }

    public String getTmaPassword() {
        return this.tmaPassword;
    }
    
    public void setTmaPassword(String tmaPassword) {
        this.tmaPassword = tmaPassword;
    }

    public String getTmaEmail() {
        return this.tmaEmail;
    }
    
    public void setTmaEmail(String tmaEmail) {
        this.tmaEmail = tmaEmail;
    }

    public Long getTmaPhone() {
        return this.tmaPhone;
    }
    
    public void setTmaPhone(Long tmaPhone) {
        this.tmaPhone = tmaPhone;
    }

    public String getTmaAddress() {
        return this.tmaAddress;
    }
    
    public void setTmaAddress(String tmaAddress) {
        this.tmaAddress = tmaAddress;
    }

    public String getTmaPasswordStatus() {
        return this.tmaPasswordStatus;
    }
    
    public void setTmaPasswordStatus(String tmaPasswordStatus) {
        this.tmaPasswordStatus = tmaPasswordStatus;
    }

    public Long getTmaWrongAttempts() {
        return this.tmaWrongAttempts;
    }
    
    public void setTmaWrongAttempts(Long tmaWrongAttempts) {
        this.tmaWrongAttempts = tmaWrongAttempts;
    }

    public String getTmaTmpPassword() {
        return this.tmaTmpPassword;
    }
    
    public void setTmaTmpPassword(String tmaTmpPassword) {
        this.tmaTmpPassword = tmaTmpPassword;
    }

    public String getTmaFax() {
        return this.tmaFax;
    }
    
    public void setTmaFax(String tmaFax) {
        this.tmaFax = tmaFax;
    }

    public String getTmaCity() {
        return this.tmaCity;
    }
    
    public void setTmaCity(String tmaCity) {
        this.tmaCity = tmaCity;
    }

    public String getTmaZip() {
        return this.tmaZip;
    }
    
    public void setTmaZip(String tmaZip) {
        this.tmaZip = tmaZip;
    }

    public String getTmaFirstname() {
        return this.tmaFirstname;
    }
    
    public void setTmaFirstname(String tmaFirstname) {
        this.tmaFirstname = tmaFirstname;
    }

    public String getTmaLastname() {
        return this.tmaLastname;
    }
    
    public void setTmaLastname(String tmaLastname) {
        this.tmaLastname = tmaLastname;
    }

    public String getTmaState() {
        return this.tmaState;
    }
    
    public void setTmaState(String tmaState) {
        this.tmaState = tmaState;
    }
   








}